import { storage } from "./storage";

const seedData = [
  {
    title: "Palak Paneer",
    description: "Creamy cottage cheese cubes in a vibrant, spiced spinach gravy — the quintessential North Indian comfort food.",
    ingredients: [
      "500g fresh spinach (palak), washed",
      "250g paneer, cut into cubes",
      "2 medium onions, finely chopped",
      "2 tomatoes, pureed",
      "1 tbsp ginger-garlic paste",
      "2 green chillies, slit",
      "1 tsp cumin seeds",
      "1 tsp garam masala",
      "1 tsp coriander powder",
      "½ tsp turmeric powder",
      "½ tsp red chilli powder",
      "3 tbsp fresh cream",
      "2 tbsp ghee or oil",
      "Salt to taste",
    ],
    instructions: [
      "Blanch spinach in boiling water for 2 minutes, then transfer immediately to ice cold water to retain its green colour.",
      "Drain the spinach and blend into a smooth puree. Set aside.",
      "Heat ghee in a kadhai over medium heat. Add cumin seeds and let them splutter.",
      "Add onions and sauté until golden brown, about 8–10 minutes. Add ginger-garlic paste and cook 2 minutes more.",
      "Add tomato puree and all dry spices. Cook until oil separates from the masala, about 8 minutes.",
      "Pour in the spinach puree and mix well. Add ½ cup water and bring to a gentle simmer.",
      "Slide in the paneer cubes and stir gently. Cook for 5 minutes so paneer absorbs the flavours.",
      "Stir in fresh cream and taste for seasoning. Serve hot with roti or steamed rice.",
    ],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    cuisineType: "North Indian",
    dietaryTags: ["Gluten-Free", "Jain Friendly"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Masoor Dal Tadka",
    description: "Earthy red lentils simmered to silky perfection, finished with a smoky tempering of ghee, cumin and dried chillies.",
    ingredients: [
      "1 cup masoor dal (red lentils), rinsed",
      "1 medium onion, finely chopped",
      "2 tomatoes, chopped",
      "1 tbsp ginger-garlic paste",
      "1 tsp turmeric powder",
      "1 tsp red chilli powder",
      "1 tsp cumin seeds",
      "2 dry red chillies",
      "1 tsp mustard seeds",
      "8–10 curry leaves",
      "2 tbsp ghee",
      "Fresh coriander for garnish",
      "Salt to taste",
      "Lemon juice to taste",
    ],
    instructions: [
      "Pressure cook lentils with turmeric, salt and 3 cups water for 3 whistles until completely soft. Mash lightly.",
      "Heat 1 tbsp oil in a pan. Sauté onions until lightly golden, then add ginger-garlic paste and cook 2 minutes.",
      "Add tomatoes and cook until they break down and oil separates, about 8 minutes.",
      "Stir in red chilli powder and add the cooked lentils. Mix well and simmer 10 minutes adding water for desired consistency.",
      "For tadka: heat ghee in a small pan until smoking. Add cumin seeds, mustard seeds, dry chillies and curry leaves.",
      "Once seeds pop, pour the sizzling tadka over the dal immediately.",
      "Finish with a squeeze of lemon juice and fresh coriander. Serve with rice or roti.",
    ],
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    cuisineType: "North Indian",
    dietaryTags: ["Gluten-Free"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Dosa with Coconut Chutney",
    description: "Crispy, lacy fermented rice and lentil crepes — South India's most beloved breakfast, served with fresh coconut chutney.",
    ingredients: [
      "2 cups parboiled rice",
      "½ cup urad dal (split black lentils)",
      "1 tsp fenugreek seeds",
      "Salt to taste",
      "Oil for cooking",
      "For Coconut Chutney: 1 cup fresh grated coconut",
      "2 green chillies",
      "1 small piece ginger",
      "½ cup roasted chana dal",
      "Salt to taste",
      "For chutney tadka: 1 tsp mustard seeds",
      "8 curry leaves",
      "1 dry red chilli",
      "1 tbsp oil",
    ],
    instructions: [
      "Soak rice, urad dal and fenugreek seeds in water overnight or for 8 hours. Grind to a smooth batter adding water gradually.",
      "Add salt and ferment the batter in a warm place for 8–12 hours until it rises and turns slightly sour.",
      "For coconut chutney: blend coconut, green chillies, ginger, roasted chana dal and salt with water to a smooth consistency.",
      "Prepare chutney tadka: heat oil, add mustard seeds, curry leaves and dry red chilli. Pour over chutney and mix.",
      "Heat a flat non-stick tawa or iron griddle on medium-high. Rub with a cut onion to season.",
      "Pour a ladleful of batter in the centre and spread in circular motion to a thin crepe.",
      "Drizzle oil around the edges and cook until golden and crisp. Fold and serve hot with coconut chutney.",
    ],
    prepTime: 20,
    cookTime: 20,
    servings: 6,
    cuisineType: "South Indian",
    dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Gujarati Dhokla",
    description: "Soft, spongy steamed gram flour cakes — light, tangy and irresistibly topped with a sweet-spicy mustard seed tempering.",
    ingredients: [
      "1 cup besan (gram flour)",
      "¾ cup yogurt, whisked",
      "1 tsp ginger-green chilli paste",
      "1 tsp lemon juice",
      "1 tsp sugar",
      "1 tsp Eno fruit salt (or baking soda)",
      "Salt to taste",
      "For tadka: 2 tbsp oil",
      "1 tsp mustard seeds",
      "8–10 curry leaves",
      "2 green chillies, slit",
      "1 tbsp sugar dissolved in ¼ cup water",
      "Fresh coriander and grated coconut for garnish",
    ],
    instructions: [
      "Mix besan, yogurt, ginger-chilli paste, lemon juice, sugar and salt into a smooth batter. Add water if needed.",
      "Grease a steaming thali or cake tin thoroughly with oil.",
      "Add Eno fruit salt to the batter, mix quickly and pour immediately into the greased tin.",
      "Steam on high heat for 15–18 minutes until a toothpick inserted comes out clean.",
      "Allow to cool 5 minutes. Cut into diamond or square shapes.",
      "For tadka: heat oil, add mustard seeds and let them pop. Add curry leaves and green chillies.",
      "Pour the sugar water into the tadka (it will splutter) and then pour over the dhokla immediately.",
      "Garnish with coriander and coconut. Serve with green chutney.",
    ],
    prepTime: 15,
    cookTime: 20,
    servings: 6,
    cuisineType: "Gujarati",
    dietaryTags: ["Gluten-Free"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Rajma Masala",
    description: "Hearty kidney beans slow-cooked in a rich, deeply spiced tomato-onion gravy — Punjab's beloved soul food.",
    ingredients: [
      "1½ cups rajma (kidney beans), soaked overnight",
      "2 large onions, finely chopped",
      "3 large tomatoes, pureed",
      "1 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "2 bay leaves",
      "1 black cardamom",
      "1 tsp coriander powder",
      "1 tsp cumin powder",
      "½ tsp turmeric",
      "1 tsp red chilli powder",
      "1 tsp garam masala",
      "2 tbsp oil or ghee",
      "Fresh coriander to garnish",
      "Salt to taste",
    ],
    instructions: [
      "Pressure cook soaked rajma with salt and 4 cups water for 5–6 whistles until completely tender. Reserve the cooking liquid.",
      "Heat oil in a heavy pan. Add cumin seeds, bay leaves and black cardamom. Let them crackle.",
      "Add onions and cook on medium heat, stirring often, until deep golden brown — about 15 minutes. Don't rush this step.",
      "Add ginger-garlic paste and cook 3 minutes until raw smell disappears.",
      "Add tomato puree and all dry spices except garam masala. Cook on medium heat stirring often until oil separates — about 12 minutes.",
      "Add the boiled rajma along with the cooking liquid. Stir well and bring to a boil.",
      "Simmer on low heat for 20–25 minutes, mashing some beans lightly to thicken the gravy.",
      "Add garam masala and adjust seasoning. Garnish with coriander and serve with steamed basmati rice.",
    ],
    prepTime: 20,
    cookTime: 60,
    servings: 5,
    cuisineType: "Punjabi",
    dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Aloo Gobi",
    description: "A rustic, dry-style curry of potatoes and cauliflower stir-fried with whole spices and fresh coriander — simple and deeply satisfying.",
    ingredients: [
      "3 medium potatoes, cut into cubes",
      "1 small cauliflower, cut into florets",
      "1 large onion, thinly sliced",
      "2 tomatoes, chopped",
      "1 tsp cumin seeds",
      "1 tsp ginger, grated",
      "1 tsp coriander powder",
      "½ tsp turmeric",
      "½ tsp red chilli powder",
      "½ tsp amchur (dry mango powder)",
      "½ tsp garam masala",
      "3 tbsp oil",
      "Fresh coriander to garnish",
      "Salt to taste",
    ],
    instructions: [
      "Parboil the potato cubes in salted water for 5 minutes until slightly tender but not fully cooked. Drain and set aside.",
      "Heat oil in a wide pan or kadhai on medium-high heat. Add cumin seeds and let them splutter.",
      "Add onions and cook until lightly golden. Add grated ginger and cook 1 minute.",
      "Add tomatoes and cook until soft. Add all dry spices except garam masala and amchur.",
      "Add cauliflower florets and potatoes. Toss gently to coat with the masala.",
      "Cover and cook on low heat for 15 minutes, stirring occasionally, until both vegetables are tender.",
      "Remove lid, increase heat and cook 3–4 minutes to dry out any moisture.",
      "Sprinkle amchur and garam masala. Toss and garnish generously with fresh coriander.",
    ],
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    cuisineType: "North Indian",
    dietaryTags: ["Vegan", "Gluten-Free", "Jain Friendly"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Sambar",
    description: "A nourishing South Indian lentil broth packed with vegetables and the complex warmth of freshly ground sambar powder.",
    ingredients: [
      "½ cup toor dal (split pigeon peas)",
      "1 cup mixed vegetables (drumstick, brinjal, carrot, pumpkin)",
      "1 tomato, quartered",
      "1 small onion, quartered",
      "1 tbsp tamarind paste",
      "2 tbsp sambar powder",
      "½ tsp turmeric",
      "For tadka: 1 tbsp oil",
      "1 tsp mustard seeds",
      "½ tsp cumin seeds",
      "10–12 curry leaves",
      "2 dry red chillies",
      "A pinch of asafoetida (hing)",
      "Salt to taste",
      "Fresh coriander to garnish",
    ],
    instructions: [
      "Pressure cook toor dal with turmeric and 2 cups water for 4 whistles until completely mushy. Whisk until smooth.",
      "In a pot, cook the vegetables in 2 cups water with turmeric and salt until just tender.",
      "Add tamarind paste diluted in ½ cup water, sambar powder, tomato and onion to the vegetables. Boil 10 minutes.",
      "Add the cooked dal to the vegetables and mix well. Add water to adjust consistency — sambar should be slightly thin.",
      "Simmer together for 10 minutes until all flavours meld. Taste and adjust salt.",
      "For tadka: heat oil until smoking. Add mustard seeds and wait for them to pop. Add cumin, dry chillies, curry leaves and hing.",
      "Pour the tadka into the sambar immediately. Garnish with coriander and serve hot with idli or rice.",
    ],
    prepTime: 15,
    cookTime: 40,
    servings: 5,
    cuisineType: "South Indian",
    dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Chana Masala",
    description: "Bold, tangy and deeply spiced chickpeas in a thick, complex masala — a Punjabi classic that pairs perfectly with bhature or rice.",
    ingredients: [
      "1½ cups chickpeas (chana), soaked overnight",
      "2 onions, finely chopped",
      "3 tomatoes, pureed",
      "1 tbsp ginger-garlic paste",
      "1 tsp cumin seeds",
      "2 tsp chana masala powder",
      "1 tsp coriander powder",
      "½ tsp red chilli powder",
      "½ tsp turmeric",
      "1 tsp amchur (dry mango powder)",
      "½ tsp garam masala",
      "2 tbsp oil",
      "Fresh coriander, onion rings and lemon wedges to serve",
      "Salt to taste",
    ],
    instructions: [
      "Pressure cook chickpeas with salt and a tea bag (for colour) in 3 cups water for 6–7 whistles until completely tender. Discard tea bag.",
      "Heat oil in a heavy pan. Add cumin seeds and let them splutter.",
      "Add onions and cook until deep golden brown — this is key to the flavour, takes about 12–15 minutes.",
      "Add ginger-garlic paste and cook 2 minutes. Add tomato puree and cook until oil separates, about 10 minutes.",
      "Add chana masala powder, coriander powder, red chilli powder and turmeric. Cook 3 minutes more.",
      "Add the cooked chickpeas with some liquid. Mix well and bring to a boil.",
      "Simmer 20 minutes, pressing some chickpeas against the pan to thicken the gravy naturally.",
      "Finish with amchur and garam masala. Serve garnished with coriander, onion rings and a squeeze of lemon.",
    ],
    prepTime: 20,
    cookTime: 55,
    servings: 5,
    cuisineType: "Punjabi",
    dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Baingan Bharta",
    description: "Smoky, fire-roasted aubergine mashed with spices and herbs — a rustic North Indian classic with complex charred depth.",
    ingredients: [
      "2 large aubergines (baingan)",
      "2 medium onions, finely chopped",
      "2 tomatoes, finely chopped",
      "4 garlic cloves, minced",
      "1 tbsp ginger, grated",
      "2 green chillies, finely chopped",
      "1 tsp cumin seeds",
      "1 tsp coriander powder",
      "½ tsp turmeric",
      "½ tsp red chilli powder",
      "½ tsp garam masala",
      "2 tbsp mustard oil (or any oil)",
      "Fresh coriander to garnish",
      "Salt to taste",
    ],
    instructions: [
      "Apply oil all over the aubergines and roast directly on a gas flame, turning with tongs, until skin is completely charred and flesh is completely soft — about 15 minutes.",
      "Place in a bowl covered with foil for 10 minutes. Peel off all charred skin under running water.",
      "Mash the flesh roughly, keeping some texture. Set aside.",
      "Heat oil in a pan. Add cumin seeds. Once they splutter, add onions and cook until golden.",
      "Add garlic, ginger and green chillies. Cook 3 minutes. Add tomatoes and cook until completely broken down.",
      "Add all dry spices and cook the masala 5 minutes more.",
      "Add the mashed aubergine and mix thoroughly. Cook 10 minutes, stirring often.",
      "Adjust salt and finish with garam masala. Garnish abundantly with fresh coriander.",
    ],
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    cuisineType: "North Indian",
    dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Rasam",
    description: "A thin, peppery, tamarind-tomato broth — South India's restorative soup that warms from within, served over rice or as a digestif.",
    ingredients: [
      "2 tbsp toor dal, cooked and mashed",
      "2 tomatoes, blended",
      "1 tbsp tamarind paste",
      "1 tsp black pepper, coarsely crushed",
      "1 tsp cumin powder",
      "1 tsp rasam powder",
      "½ tsp turmeric",
      "3 garlic cloves, crushed",
      "For tadka: 1 tbsp ghee",
      "1 tsp mustard seeds",
      "A pinch of asafoetida",
      "10 curry leaves",
      "2 dry red chillies",
      "Fresh coriander to garnish",
      "Salt to taste",
    ],
    instructions: [
      "Combine tomato puree, tamarind paste, turmeric, salt and 2 cups water in a pot. Bring to a boil.",
      "Add crushed garlic, black pepper, cumin powder and rasam powder. Simmer 10 minutes.",
      "Add the cooked, mashed dal and mix well. Thin with more water — rasam should be very watery.",
      "Bring to a full rolling boil for 2 minutes. The top should be frothy. Remove from heat immediately — don't overcook.",
      "For tadka: heat ghee until smoking. Add mustard seeds and wait for them to pop.",
      "Add asafoetida, curry leaves and dry chillies. They will crisp up in seconds.",
      "Pour tadka into the rasam. Garnish with coriander and serve immediately over rice or in small cups as a soup.",
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    cuisineType: "South Indian",
    dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Paneer Butter Masala",
    description: "Silky, mildly spiced cottage cheese in a velvety tomato-cashew gravy with butter and cream — India's most celebrated restaurant curry.",
    ingredients: [
      "300g paneer, cubed",
      "2 onions, roughly chopped",
      "4 tomatoes, roughly chopped",
      "15 cashews, soaked 30 minutes",
      "1 tbsp ginger-garlic paste",
      "2 tsp kashmiri red chilli powder",
      "1 tsp coriander powder",
      "1 tsp sugar",
      "½ tsp garam masala",
      "3 tbsp butter",
      "4 tbsp fresh cream",
      "1 bay leaf",
      "2 green cardamoms",
      "Salt to taste",
      "Dried fenugreek leaves (kasuri methi) to finish",
    ],
    instructions: [
      "Heat 1 tbsp butter in a pan. Sauté onions until translucent. Add tomatoes and cashews and cook until tomatoes are soft.",
      "Cool the mixture and blend into a completely smooth, silky puree. Strain through a sieve for extra smoothness.",
      "In the same pan, heat remaining butter. Add bay leaf, cardamom and ginger-garlic paste. Cook 2 minutes.",
      "Add the strained tomato-cashew puree. Add kashmiri chilli powder, coriander powder and sugar.",
      "Cook the gravy on medium heat for 15 minutes until it thickens and butter begins to float on top.",
      "Add paneer cubes and fold gently. Simmer 5 minutes.",
      "Stir in fresh cream and adjust seasoning. Crush dried fenugreek leaves between palms and stir in.",
      "Finish with a swirl of cream and serve with buttery naan or fragrant basmati rice.",
    ],
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    cuisineType: "North Indian",
    dietaryTags: ["Gluten-Free", "Jain Friendly"],
    imageUrl: null,
    authorId: null,
  },
  {
    title: "Khichdi",
    description: "The ultimate Indian comfort food — a wholesome, golden one-pot of rice and lentils cooked with warming spices. Nourishing and healing.",
    ingredients: [
      "½ cup basmati rice, rinsed",
      "½ cup moong dal (yellow split lentils), rinsed",
      "1 small onion, finely chopped",
      "1 tomato, chopped",
      "1 tsp ginger, grated",
      "1 tsp cumin seeds",
      "¼ tsp turmeric",
      "¼ tsp asafoetida (hing)",
      "1 tsp ghee",
      "2 tbsp extra ghee to serve",
      "Salt to taste",
      "Fresh coriander to garnish",
    ],
    instructions: [
      "Dry roast moong dal in a pan for 3–4 minutes until lightly golden and fragrant. Set aside.",
      "Heat ghee in a pressure cooker. Add cumin seeds and asafoetida. When seeds crackle, add onions.",
      "Sauté onions until translucent. Add ginger and cook 1 minute. Add tomatoes and cook 3 minutes.",
      "Add turmeric and salt. Add the rice and roasted moong dal. Mix to coat with the ghee and spices.",
      "Add 3 cups water. Pressure cook for 3 whistles, then simmer on low for 5 minutes.",
      "Allow pressure to release naturally. Open and mash gently — khichdi should be creamy, not grainy.",
      "Thin with hot water if needed. Serve in bowls, topped generously with ghee and fresh coriander.",
    ],
    prepTime: 10,
    cookTime: 25,
    servings: 3,
    cuisineType: "Pan-Indian",
    dietaryTags: ["Gluten-Free"],
    imageUrl: null,
    authorId: null,
  },
];

export async function seedRecipes() {
  try {
    const count = await storage.recipeCount();
    if (count > 0) {
      console.log(`[seed] Database already has ${count} recipes. Skipping seed.`);
      return;
    }
    console.log("[seed] Seeding recipes...");
    for (const recipe of seedData) {
      await storage.createRecipe(recipe as any);
    }
    console.log(`[seed] Seeded ${seedData.length} recipes successfully.`);
  } catch (err) {
    console.error("[seed] Error seeding recipes:", err);
  }
}
