function yt(title: string) {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(title + " indian sweet recipe")}`;
}

export const dessertSeedData = [
  // ── BENGALI SWEETS ──────────────────────────────────────────────────────────
  {
    title: "Rasgulla", category: "dessert",
    description: "Pillowy soft cottage cheese balls boiled in light sugar syrup — Bengal's most iconic and beloved mithai.",
    ingredients: ["1 litre full-fat milk","2 tbsp lemon juice or vinegar","1½ cups sugar","4 cups water","1 tsp rose water","A pinch of saffron"],
    instructions: [
      "Boil milk and add lemon juice slowly while stirring until whey separates clearly from chenna.",
      "Drain through muslin cloth, wash the chenna under cold water to remove sourness, and hang for 30 minutes.",
      "Knead the chenna on a flat surface for 8–10 minutes until completely smooth and soft with no graininess.",
      "Roll into smooth balls the size of large marbles — ensure no cracks on the surface.",
      "Prepare sugar syrup in a wide pan: boil sugar and water together. Gently slide in chenna balls.",
      "Cover and cook on medium heat for 18–20 minutes until the rasgullas puff up and look spongy.",
      "Cool in syrup. Add rose water. Chill and serve.",
    ],
    prepTime: 45, cookTime: 25, servings: 20,
    cuisineType: "Bengali", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Rasgulla"),
  },
  {
    title: "Rasmalai", category: "dessert",
    description: "Flattened cottage cheese discs soaking in saffron and cardamom-scented thickened milk — the queen of Bengali sweets.",
    ingredients: ["1 litre full-fat milk (for chenna)","2 tbsp lemon juice","1 litre full-fat milk (for ras)","½ cup sugar","½ tsp cardamom powder","A generous pinch of saffron","2 tbsp pistachios, sliced","2 tbsp almonds, slivered","1 tsp rose water"],
    instructions: [
      "Make chenna from 1 litre milk, knead smooth, and shape into small flat discs.",
      "Boil discs in thin sugar syrup (1 cup sugar, 4 cups water) covered for 15 minutes until spongy. Remove and squeeze gently.",
      "Thicken the other 1 litre milk on medium heat, stirring frequently, until reduced to half.",
      "Add sugar, saffron, and cardamom. Stir until sugar dissolves. Add rose water.",
      "Gently place the spongy discs into the thickened milk (ras).",
      "Simmer 5 minutes. Cool completely then refrigerate for at least 2 hours.",
      "Serve chilled, garnished with pistachios and almonds.",
    ],
    prepTime: 30, cookTime: 40, servings: 10,
    cuisineType: "Bengali", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Rasmalai"),
  },
  {
    title: "Mishti Doi", category: "dessert",
    description: "Caramelised jaggery-sweetened baked yogurt from Bengal — thick, creamy and uniquely fragrant with earthen flavour.",
    ingredients: ["1 litre full-fat milk","4 tbsp jaggery or raw sugar","2 tbsp plain yogurt (as starter)","A pinch of cardamom powder"],
    instructions: [
      "Heat milk and reduce it to three-quarters of original volume, stirring often.",
      "Dissolve jaggery in the warm milk — the milk will turn a caramel golden colour.",
      "Cool to lukewarm (40°C). Add yogurt starter and cardamom. Mix gently.",
      "Pour into small earthen pots or bowls. Cover with foil.",
      "Set in a warm place for 6–8 hours or overnight until firmly set.",
      "Refrigerate for 2 hours before serving. The texture should be creamy yet firm.",
    ],
    prepTime: 10, cookTime: 30, servings: 6,
    cuisineType: "Bengali", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mishti Doi"),
  },
  {
    title: "Chhena Poda", category: "dessert",
    description: "Odisha's burnt cottage cheese dessert — caramelised, slightly smoky and fragrant with cardamom and camphor. Lord Jagannath's favourite.",
    ingredients: ["500g fresh chenna (cottage cheese)","¾ cup sugar","2 tbsp semolina (rava)","½ tsp cardamom powder","A tiny pinch of camphor (edible)","2 tbsp cashews, chopped","1 tbsp ghee"],
    instructions: [
      "Preheat oven to 200°C. Grease a baking tin with ghee.",
      "Mix chenna, sugar, semolina, cardamom, and camphor together until smooth.",
      "Fold in chopped cashews. Pour into the greased tin.",
      "Sprinkle a little sugar on top to help caramelisation.",
      "Bake at 200°C for 50–60 minutes until the top is a deep golden-brown and a skewer comes out clean.",
      "Cool completely. Invert on a plate. The bottom will be caramelised dark brown — this is correct.",
      "Slice and serve. Keeps well for 2–3 days at room temperature.",
    ],
    prepTime: 15, cookTime: 60, servings: 8,
    cuisineType: "East Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Chhena Poda"),
  },
  {
    title: "Sandesh", category: "dessert",
    description: "Delicate melt-in-mouth cottage cheese sweet from Bengal — subtly flavoured with rose and saffron, shaped into petals.",
    ingredients: ["500g fresh chenna","½ cup powdered sugar","½ tsp cardamom powder","A pinch of saffron in 1 tbsp warm milk","1 tsp rose water","Pistachios for garnish"],
    instructions: [
      "Knead fresh chenna on a flat surface for 5 minutes until smooth and free of lumps.",
      "Add powdered sugar and knead again until it comes together into a dough.",
      "Cook this mixture in a heavy pan on low heat for 5–7 minutes, stirring continuously until it leaves the sides.",
      "Add saffron milk, cardamom, and rose water. Mix well.",
      "Remove from heat. Cool slightly, then press into moulds or shape by hand.",
      "Garnish with a sliver of pistachio pressed into the top.",
      "Refrigerate 1 hour before serving.",
    ],
    prepTime: 20, cookTime: 10, servings: 15,
    cuisineType: "Bengali", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Sandesh Bengali sweet"),
  },
  {
    title: "Chum Chum", category: "dessert",
    description: "Elongated cottage cheese sweet from Bengal, soaked in sugar syrup and rolled in khoya or coconut — festive and celebratory.",
    ingredients: ["1 litre milk (for chenna)","2 tbsp lemon juice","1½ cups sugar","4 cups water","½ cup khoya or dessicated coconut","1 tsp rose water","A few drops of food colour (optional)"],
    instructions: [
      "Prepare chenna, knead smooth, and shape into elongated oval fingers.",
      "Cook in thin sugar syrup (covered) for 15 minutes. Allow to sponge up syrup as they cool.",
      "For white chum chum: roll in mawa or dessicated coconut.",
      "For coloured: lightly colour the outer coating.",
      "Slit gently and stuff with sweetened khoya mixed with cardamom.",
      "Arrange on a plate and chill before serving.",
    ],
    prepTime: 40, cookTime: 20, servings: 12,
    cuisineType: "Bengali", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Chum Chum Bengali sweet"),
  },
  {
    title: "Pantua", category: "dessert",
    description: "Bengal's dark fried milk dumplings — cousin to gulab jamun but made with chenna, soaked in saffron syrup.",
    ingredients: ["500g chenna (fresh cottage cheese)","3 tbsp all-purpose flour","A pinch of baking powder","Oil or ghee for frying","1½ cups sugar","2 cups water","½ tsp cardamom powder","A few saffron strands"],
    instructions: [
      "Mix chenna, flour, and baking powder. Knead into a smooth soft dough.",
      "Prepare thin sugar syrup by boiling sugar, water, cardamom, and saffron together.",
      "Divide dough into small smooth balls ensuring no cracks.",
      "Deep fry on low-medium heat until deep mahogany brown, rolling continuously — about 8 minutes.",
      "Drain and immediately immerse in warm sugar syrup.",
      "Soak for at least 2 hours. They will absorb syrup and become soft and spongy.",
      "Serve warm or at room temperature.",
    ],
    prepTime: 20, cookTime: 30, servings: 15,
    cuisineType: "Bengali", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Pantua Bengali sweet"),
  },
  // ── LADOOS ──────────────────────────────────────────────────────────────────
  {
    title: "Boondi Ladoo", category: "dessert",
    description: "Golden gram flour droplets soaked in cardamom sugar syrup and rolled into round ladoos — the most celebrated Indian festival sweet.",
    ingredients: ["2 cups besan (chickpea flour)","Water to make batter","Oil for deep frying","2 cups sugar","1 cup water","1 tsp cardamom powder","10 cashews, halved","2 tbsp raisins","A pinch of saffron"],
    instructions: [
      "Make a smooth, flowing batter by mixing besan with water — it should flow through a perforated spoon easily.",
      "Heat oil. Drop batter through a boondi jharni (perforated ladle) to make tiny spherical droplets. Fry until golden.",
      "Make a one-string sugar syrup: boil sugar, water and saffron. Test by pulling a thread between fingers.",
      "Remove from heat. Add fried boondi, cardamom, cashews and raisins. Mix quickly.",
      "When cool enough to handle, wet hands with water and shape into firm round balls.",
      "Work fast as the mixture hardens as it cools.",
      "Allow to set for 30 minutes. Store in an airtight container.",
    ],
    prepTime: 20, cookTime: 30, servings: 20,
    cuisineType: "North Indian", dietaryTags: ["Vegan"],
    imageUrl: null, youtubeUrl: yt("Boondi Ladoo"),
  },
  {
    title: "Besan Ladoo", category: "dessert",
    description: "Rich, melt-in-mouth gram flour ladoos roasted slowly in ghee with cardamom — essential Diwali mithai from North India.",
    ingredients: ["2 cups besan (chickpea flour)","¾ cup ghee","1 cup powdered sugar","1 tsp cardamom powder","10 cashews, chopped","2 tbsp raisins"],
    instructions: [
      "Heat ghee in a heavy pan on low flame. Add besan.",
      "Roast on low heat, stirring continuously for 20–25 minutes until besan turns golden and the raw smell disappears completely.",
      "The mixture will become liquid initially and then thicken as moisture evaporates.",
      "Remove from heat and cool for 10 minutes — it should be warm but handleable.",
      "Add powdered sugar, cardamom, cashews and raisins. Mix thoroughly.",
      "Shape into round balls while still warm. If too crumbly, add a few drops of warm ghee.",
      "Cool completely before storing.",
    ],
    prepTime: 10, cookTime: 30, servings: 20,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Besan Ladoo"),
  },
  {
    title: "Motichoor Ladoo", category: "dessert",
    description: "Fine-grain boondi cooked into perfectly spherical, saffron-gold ladoos — softer and more delicate than regular boondi ladoo.",
    ingredients: ["2 cups besan","Water for thin batter","Oil for frying","2 cups sugar","1 cup water","1 tsp cardamom powder","Saffron strands","A few drops of orange food colour","Rose water"],
    instructions: [
      "Make a very thin, pourable batter with besan — thinner than regular boondi batter.",
      "Use a fine-holed jharni or a spoon to drizzle batter into hot oil — boondi should be tiny pearl-like spheres.",
      "Fry until just lightly golden (not dark). Drain.",
      "Prepare sugar syrup to one-string consistency. Add colour, saffron, and rose water.",
      "Add boondi to syrup while syrup is hot. Mash slightly with the back of a spoon.",
      "Cool to handling temperature. Shape into round balls by pressing firmly.",
      "Decorate with a pistachio or silver vark.",
    ],
    prepTime: 25, cookTime: 30, servings: 20,
    cuisineType: "North Indian", dietaryTags: ["Vegan"],
    imageUrl: null, youtubeUrl: yt("Motichoor Ladoo"),
  },
  {
    title: "Coconut Ladoo", category: "dessert",
    description: "Quick five-ingredient coconut sweet — fresh coconut cooked with condensed milk and cardamom, shaped in minutes.",
    ingredients: ["2 cups fresh grated coconut (or dessicated)","½ cup sweetened condensed milk","½ tsp cardamom powder","2 tbsp ghee","Dessicated coconut for rolling"],
    instructions: [
      "Heat ghee in a pan. Add grated coconut and stir for 2 minutes.",
      "Add condensed milk and cardamom. Cook on medium-low heat, stirring continuously.",
      "Cook until the mixture thickens and leaves the sides of the pan, about 8 minutes.",
      "Remove from heat. Cool until handleable.",
      "Grease hands with ghee and roll into smooth balls.",
      "Roll each ball in dessicated coconut. Decorate with a pistachio.",
      "Refrigerate 30 minutes to firm up.",
    ],
    prepTime: 10, cookTime: 12, servings: 15,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Coconut Ladoo"),
  },
  {
    title: "Rava Ladoo", category: "dessert",
    description: "Roasted semolina ladoos with cashews and raisins — quick, nutty and fragrant with ghee and cardamom.",
    ingredients: ["2 cups fine semolina (rava)","¾ cup sugar, powdered","½ cup ghee","½ tsp cardamom powder","10 cashews, chopped","2 tbsp raisins","2 tbsp grated coconut (optional)"],
    instructions: [
      "Dry roast semolina in a pan on low heat for 10 minutes until lightly golden and fragrant.",
      "Heat ghee and add cashews and raisins. Fry briefly until golden.",
      "Mix roasted rava with powdered sugar, cardamom, cashews, raisins, and coconut.",
      "Add warm ghee to the rava mixture. Mix thoroughly.",
      "While still warm, press firmly into round balls. If crumbly, add a few drops of warm milk.",
      "Shape quickly — the mixture hardens as it cools.",
      "Store in an airtight container at room temperature for up to 1 week.",
    ],
    prepTime: 10, cookTime: 15, servings: 18,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Rava Ladoo"),
  },
  {
    title: "Til Ladoo", category: "dessert",
    description: "Sesame and jaggery ladoos eaten on Makar Sankranti — crunchy, nutty and packed with iron and warmth.",
    ingredients: ["2 cups white sesame seeds","1 cup jaggery, grated","2 tbsp peanuts, roasted","1 tsp ghee","½ tsp cardamom powder","A pinch of dry ginger powder"],
    instructions: [
      "Dry roast sesame seeds on low heat until they splutter and turn lightly golden. Cool.",
      "Roast peanuts and crush coarsely.",
      "Melt jaggery in 2 tbsp water on medium heat until it reaches soft ball stage — a drop in cold water should form a soft ball.",
      "Remove from heat. Quickly add sesame seeds, peanuts, cardamom, and dry ginger.",
      "Mix well. With greased hands, quickly shape into small balls.",
      "Work fast as the mixture hardens quickly as it cools.",
      "Store in an airtight tin. Keeps for 2 weeks.",
    ],
    prepTime: 10, cookTime: 15, servings: 20,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Til Ladoo Sesame Jaggery"),
  },
  {
    title: "Peanut Ladoo", category: "dessert",
    description: "Roasted peanuts and jaggery pressed into satisfying ladoos — a protein-rich, natural, minimally sweetened energy ball.",
    ingredients: ["2 cups roasted peanuts, skinned","¾ cup jaggery, grated","½ tsp cardamom powder","1 tsp ghee"],
    instructions: [
      "Grind half the roasted peanuts into a coarse powder. Keep the rest whole or halved.",
      "Melt jaggery in 2 tbsp water to soft ball stage.",
      "Remove from heat. Add peanut powder, whole peanuts, cardamom, and ghee.",
      "Mix quickly and shape into balls while warm.",
      "These ladoos are firm at room temperature — no refrigeration needed.",
      "Store in an airtight jar for up to 2 weeks.",
    ],
    prepTime: 10, cookTime: 10, servings: 15,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Peanut Ladoo Jaggery"),
  },
  // ── BARFIS ──────────────────────────────────────────────────────────────────
  {
    title: "Kaju Katli", category: "dessert",
    description: "Thin diamond-shaped cashew sweet with a smooth, melt-in-mouth texture — India's most gifted and prized mithai.",
    ingredients: ["2 cups cashew nuts","½ cup sugar","¼ cup water","A pinch of cardamom","1 tsp ghee","Silver vark (edible silver leaf) for decoration"],
    instructions: [
      "Grind raw cashews to a fine powder in a dry grinder. Do not over-grind or it will release oil.",
      "Boil sugar and water to one-string consistency.",
      "Add cashew powder on very low heat, stirring constantly.",
      "Cook until the mixture leaves the sides and forms a soft dough — about 5 minutes.",
      "Remove from heat. Add cardamom and ghee. Knead gently while warm.",
      "Roll between two parchment sheets to 4mm thickness. Apply silver vark.",
      "Cool 20 minutes and cut into diamond shapes with a sharp knife.",
    ],
    prepTime: 15, cookTime: 15, servings: 30,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kaju Katli"),
  },
  {
    title: "Milk Barfi", category: "dessert",
    description: "Simple yet luxurious condensed milk and khoya barfi — creamy, fragrant and cuts into clean perfect squares.",
    ingredients: ["1 cup khoya (mawa), grated","½ cup sweetened condensed milk","½ cup milk powder","½ tsp cardamom powder","1 tbsp ghee","Pistachios for garnish"],
    instructions: [
      "Heat ghee in a heavy pan. Add khoya and stir on low heat until it melts.",
      "Add condensed milk and milk powder. Stir continuously on low heat.",
      "Cook for 10–12 minutes until the mixture thickens and leaves the sides of the pan.",
      "Add cardamom. Mix well.",
      "Pour into a greased plate. Spread evenly. Press pistachios on top.",
      "Cool completely for 1 hour before cutting into squares or diamonds.",
    ],
    prepTime: 5, cookTime: 15, servings: 20,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Milk Barfi"),
  },
  {
    title: "Coconut Barfi", category: "dessert",
    description: "Two-tone coconut sweet — a layer of golden jaggery coconut and white sugar coconut fused together into a beautiful barfi.",
    ingredients: ["3 cups fresh grated coconut","1 cup sugar","½ cup jaggery","½ tsp cardamom powder","1 tbsp ghee","A pinch of saffron"],
    instructions: [
      "Divide coconut in half.",
      "Make white layer: cook one half with sugar in a pan, stirring until dry. Add cardamom.",
      "Make golden layer: cook other half with jaggery and ghee until dry. Add saffron.",
      "Grease a plate. Spread white layer. Press golden layer on top.",
      "Cover with another plate and press firmly to fuse layers together.",
      "Cool for 2 hours. Cut into squares — the two-tone layers will be visible.",
    ],
    prepTime: 15, cookTime: 20, servings: 20,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Coconut Barfi"),
  },
  {
    title: "Pista Barfi", category: "dessert",
    description: "Elegant vivid green pistachio fudge — subtly fragrant with rose water and cardamom, decorated with silver leaf.",
    ingredients: ["2 cups pistachios, soaked and peeled","½ cup sugar","¼ cup water","½ tsp cardamom powder","1 tsp rose water","1 tbsp ghee","Silver vark for garnish"],
    instructions: [
      "Soak pistachios in warm water for 1 hour. Peel the skins.",
      "Grind peeled pistachios to a fine powder. The natural green colour should show.",
      "Cook sugar and water to one-string consistency.",
      "Add pistachio powder and cook on very low heat, stirring until dough forms.",
      "Add rose water, cardamom, and ghee. Knead gently.",
      "Roll to 5mm thickness on parchment. Apply silver vark.",
      "Cool and cut into diamond or square shapes.",
    ],
    prepTime: 70, cookTime: 15, servings: 25,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Pista Barfi Pistachio"),
  },
  {
    title: "Besan Barfi", category: "dessert",
    description: "Chickpea flour barfi slow-roasted in ghee — deeply nutty, crumbly and richly flavoured with cardamom.",
    ingredients: ["2 cups besan","¾ cup ghee","1 cup sugar","¼ cup water","1 tsp cardamom powder","10 cashews for garnish"],
    instructions: [
      "Roast besan in ghee on low heat for 25 minutes, stirring constantly, until deep golden and fragrant.",
      "Separately make sugar syrup to one-string consistency.",
      "Remove besan from heat. Pour syrup over it. Add cardamom. Mix quickly.",
      "Pour into greased plate. Spread evenly. Decorate with cashews.",
      "Cool 2 hours before cutting into squares.",
      "Store in an airtight container up to 1 week.",
    ],
    prepTime: 5, cookTime: 35, servings: 20,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Besan Barfi"),
  },
  // ── HALWAS ──────────────────────────────────────────────────────────────────
  {
    title: "Moong Dal Halwa", category: "dessert",
    description: "Rajasthani slow-cooked yellow lentil halwa — deeply nutty, ghee-soaked and saffron-fragrant. A labour of love worth every minute.",
    ingredients: ["1 cup yellow moong dal, soaked 3 hours","½ cup ghee","1 cup sugar","2 cups water","½ tsp cardamom powder","A generous pinch of saffron","2 tbsp almonds and cashews","1 tbsp raisins"],
    instructions: [
      "Drain soaked moong dal and grind to a coarse paste without adding water.",
      "Heat ghee in a heavy pan. Add dal paste and cook on low-medium heat, stirring continuously.",
      "Keep cooking and stirring for 40–45 minutes — the mixture will first turn yellow, then golden brown.",
      "Meanwhile, make sugar syrup by boiling sugar and water together with saffron.",
      "When dal is golden and aromatic, carefully pour in the hot sugar syrup. It will splutter — stir quickly.",
      "Cook until all liquid is absorbed and ghee starts to separate. Add cardamom.",
      "Garnish with fried nuts and raisins. Serve hot.",
    ],
    prepTime: 180, cookTime: 50, servings: 8,
    cuisineType: "Rajasthani", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Moong Dal Halwa"),
  },
  {
    title: "Badam Halwa", category: "dessert",
    description: "Sumptuous almond pudding in saffron-kissed ghee — South India's most treasured festive sweet, dense and utterly luxurious.",
    ingredients: ["1 cup almonds, soaked and peeled","¾ cup sugar","¼ cup water","3 tbsp ghee","½ tsp cardamom powder","A generous pinch of saffron in 2 tbsp warm milk","A few drops of yellow food colour (optional)"],
    instructions: [
      "Soak almonds overnight. Peel the skins. Grind to a smooth paste with 2 tbsp water.",
      "Heat ghee in a heavy pan. Add almond paste and cook on medium heat, stirring.",
      "Make sugar syrup with sugar and water. Add saffron milk.",
      "Pour syrup into the almond mixture. Stir continuously on medium heat.",
      "Cook until halwa thickens, turns golden, and ghee separates from the sides — about 20 minutes.",
      "Add cardamom. The halwa should hold its shape when a spoonful is dropped on a plate.",
      "Serve warm garnished with slivered almonds and pistachios.",
    ],
    prepTime: 480, cookTime: 25, servings: 6,
    cuisineType: "South Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Badam Halwa"),
  },
  {
    title: "Bread Halwa", category: "dessert",
    description: "Quick and indulgent bread pudding halwa — torn bread pieces fried in ghee and cooked with condensed milk and saffron.",
    ingredients: ["6 thick bread slices, crusts removed","3 tbsp ghee","½ cup sugar","1 cup milk","½ cup condensed milk","½ tsp cardamom powder","Saffron strands","2 tbsp cashews and raisins"],
    instructions: [
      "Tear bread into small pieces. Fry in ghee in a heavy pan until golden on all sides.",
      "In the same pan, add milk, condensed milk, and sugar. Stir to mix.",
      "Add saffron and cook on medium heat, mashing the bread gently.",
      "Fry cashews and raisins in a separate spoon of ghee. Add to halwa.",
      "Cook until the mixture comes together and becomes thick, about 10 minutes.",
      "Add cardamom. The halwa should look glossy.",
      "Serve warm.",
    ],
    prepTime: 10, cookTime: 20, servings: 6,
    cuisineType: "North Indian", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Bread Halwa"),
  },
  {
    title: "Lauki Ka Halwa", category: "dessert",
    description: "Bottle gourd cooked slow in milk until creamy and sweet — a surprisingly delicious halwa light enough for everyday enjoyment.",
    ingredients: ["500g bottle gourd (lauki), peeled and grated","½ litre full-fat milk","½ cup sugar","3 tbsp ghee","½ tsp cardamom powder","2 tbsp khoya (optional)","Cashews for garnish"],
    instructions: [
      "Squeeze out excess water from grated lauki.",
      "Cook lauki in milk on medium heat, stirring often, until milk is absorbed and lauki is tender — 25 minutes.",
      "Add sugar and ghee. Stir continuously on medium heat.",
      "Cook until the halwa leaves the sides and comes together — 15 more minutes.",
      "Add khoya if using, and cardamom. Mix well.",
      "Fry cashews in a little ghee and add on top.",
      "Serve hot or warm.",
    ],
    prepTime: 20, cookTime: 45, servings: 6,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Lauki Ka Halwa"),
  },
  {
    title: "Banana Halwa", category: "dessert",
    description: "Kerala-style ripe banana halwa — caramelised in ghee until deep, jammy and glossy with the sweetness of ripe nendran bananas.",
    ingredients: ["6 ripe nendran bananas (or ripe plantains)","1 cup sugar","4 tbsp ghee","½ tsp cardamom powder","A pinch of salt","Cashews and raisins for garnish"],
    instructions: [
      "Peel and mash bananas to a smooth pulp.",
      "Cook banana pulp in a heavy pan on medium heat, stirring until it reduces — 10 minutes.",
      "Add sugar and ghee. Stir continuously on medium-high heat.",
      "The halwa will turn darker and caramelise as water evaporates — about 25–30 minutes.",
      "Keep stirring to prevent burning. The halwa is done when it is very thick, shiny, and leaves the pan sides.",
      "Add cardamom and salt. Fry cashews and raisins in ghee and add.",
      "Spread in a greased dish. Cool and cut into pieces, or serve warm.",
    ],
    prepTime: 10, cookTime: 40, servings: 8,
    cuisineType: "South Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Banana Halwa Kerala"),
  },
  // ── NORTH INDIAN SWEETS ──────────────────────────────────────────────────────
  {
    title: "Mysore Pak", category: "dessert",
    description: "Karnataka's legendary melt-in-mouth besan sweet — ghee-soaked, fragrant and porous, consumed in just one blissful bite.",
    ingredients: ["1 cup besan (chickpea flour)","1 cup sugar","¾ cup water","1 cup ghee (plus more as needed)","½ tsp cardamom powder"],
    instructions: [
      "Sieve besan. Slowly add 6 tbsp warm ghee and mix to a smooth paste.",
      "Cook sugar and water to one-string syrup. Keep the syrup hot.",
      "Add besan paste to the hot syrup on medium heat, stirring briskly.",
      "Continue stirring while adding the remaining ghee in small batches, a few tablespoons at a time.",
      "The mixture will bubble and foam — keep stirring. When it no longer sticks to the pan and appears honeycombed, it's ready.",
      "Quickly pour into a greased plate — it sets within minutes.",
      "Cut into squares while still slightly warm using a sharp knife. Cool before removing.",
    ],
    prepTime: 10, cookTime: 20, servings: 20,
    cuisineType: "South Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mysore Pak"),
  },
  {
    title: "Jalebi", category: "dessert",
    description: "Crispy, pretzel-shaped deep-fried spirals soaked in cardamom and saffron sugar syrup — India's most festive street sweet.",
    ingredients: ["1 cup all-purpose flour","2 tbsp cornflour","¼ tsp baking powder","½ cup yogurt","Water to make batter","Oil for frying","1½ cups sugar","¾ cup water","½ tsp cardamom powder","Saffron strands","A few drops of orange food colour"],
    instructions: [
      "Mix flour, cornflour, baking powder, yogurt, and water to a smooth, flowing batter. Rest 30 minutes (or ferment overnight).",
      "Make sugar syrup: boil sugar, water, saffron, and cardamom to one-string consistency. Keep warm.",
      "Heat oil in a flat pan to 170°C. Add colour to batter.",
      "Pour batter into a squeeze bottle or piping bag. Pipe spirals into the hot oil.",
      "Fry 2 minutes per side until crisp and golden.",
      "Drain briefly and immediately immerse in warm sugar syrup for 1 minute.",
      "Serve immediately while warm and crispy.",
    ],
    prepTime: 40, cookTime: 30, servings: 15,
    cuisineType: "North Indian", dietaryTags: ["Vegan"],
    imageUrl: null, youtubeUrl: yt("Jalebi"),
  },
  {
    title: "Malpua", category: "dessert",
    description: "Pan-fried sweet pancakes soaked in saffron syrup and served with thickened rabri — a festive Holi delicacy.",
    ingredients: ["1 cup all-purpose flour","2 tbsp semolina","½ cup khoya, crumbled","1 tsp fennel seeds","Milk to make batter","Ghee or oil for shallow frying","1½ cups sugar","¾ cup water","Saffron and cardamom for syrup"],
    instructions: [
      "Mix flour, semolina, khoya, and fennel seeds. Add enough milk to make a thick, pourable pancake batter.",
      "Rest the batter for 30 minutes.",
      "Prepare sugar syrup with saffron and cardamom.",
      "Heat ghee in a flat pan. Pour ladlefuls of batter to make small thick pancakes.",
      "Fry on medium heat until golden on both sides — about 3 minutes per side.",
      "Drain and immediately dip in sugar syrup for 1 minute.",
      "Serve with chilled rabri and a sprinkle of pistachios.",
    ],
    prepTime: 40, cookTime: 20, servings: 10,
    cuisineType: "North Indian", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Malpua sweet"),
  },
  {
    title: "Shahi Tukda", category: "dessert",
    description: "Mughal royal bread pudding — fried bread triangles soaked in sugar syrup, covered in saffron rabri and topped with silver leaf.",
    ingredients: ["6 bread slices, cut into triangles","Ghee for frying","1 litre full-fat milk (for rabri)","½ cup sugar","Saffron and cardamom","1 cup thin sugar syrup","Silver vark and pistachios for garnish"],
    instructions: [
      "Fry bread triangles in ghee until deep golden. Drain on paper.",
      "Make rabri: reduce 1 litre milk on medium heat with sugar and saffron, stirring every few minutes, until it thickens to half — about 30 minutes.",
      "Dip each fried bread piece in thin sugar syrup for 1 minute.",
      "Arrange in a serving dish. Pour thick rabri over.",
      "Refrigerate 1 hour.",
      "Serve chilled topped with pistachios, almonds, and silver vark.",
    ],
    prepTime: 15, cookTime: 45, servings: 6,
    cuisineType: "North Indian", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Shahi Tukda"),
  },
  {
    title: "Kalakand", category: "dessert",
    description: "Grainy, crumbly Indian milk cake made from reduced milk and paneer — subtly sweet with a distinctive chewy texture.",
    ingredients: ["1 litre full-fat milk","1 cup paneer, crumbled","½ cup sugar","½ tsp cardamom powder","A pinch of saffron","Pistachios for garnish"],
    instructions: [
      "Boil milk in a heavy pan. Add crumbled paneer — the mixture will separate and granulate.",
      "Cook on medium-high heat, stirring continuously until very thick and the moisture evaporates — 25 minutes.",
      "Add sugar and stir for 10 more minutes until the mixture leaves the pan sides.",
      "Add saffron and cardamom.",
      "Pour into a greased plate. Press down to compact.",
      "Decorate with pistachios.",
      "Cool completely (1–2 hours). Cut into squares.",
    ],
    prepTime: 10, cookTime: 40, servings: 12,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kalakand"),
  },
  {
    title: "Peda", category: "dessert",
    description: "Soft, melt-in-mouth milk fudge flavoured with cardamom and saffron — simple yet exquisite, offered to deities across India.",
    ingredients: ["1 cup khoya (mawa)","¼ cup powdered sugar","½ tsp cardamom powder","A pinch of saffron in 1 tsp warm milk","Pistachios for pressing into top"],
    instructions: [
      "Crumble khoya in a heavy pan. Cook on low heat, stirring until it melts and begins to change colour slightly — 5 minutes.",
      "Remove from heat. Cool slightly.",
      "Mix in powdered sugar, cardamom, and saffron milk. Mix well.",
      "The mixture should be pliable like soft dough.",
      "Divide into portions. Roll into balls and flatten slightly to a disc shape.",
      "Press a pistachio into the centre of each peda.",
      "Refrigerate 30 minutes to firm up. Serve at room temperature.",
    ],
    prepTime: 10, cookTime: 10, servings: 15,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Peda"),
  },
  {
    title: "Kesar Peda", category: "dessert",
    description: "Saffron-golden milk fudge from Mathura — fragrant, soft and deeply orange-yellow from generous kesar.",
    ingredients: ["1 cup khoya","¼ cup sweetened condensed milk","¼ cup powdered sugar","½ tsp cardamom powder","1 tsp saffron soaked in 2 tbsp warm milk","Pistachios for garnish"],
    instructions: [
      "Cook khoya and condensed milk together in a heavy pan on low heat for 8 minutes, stirring.",
      "Add powdered sugar and kesar milk. Stir for 5 more minutes.",
      "The mixture will turn vivid golden-yellow from the saffron.",
      "Remove from heat and cool until handleable.",
      "Shape into small round discs. Press a pistachio sliver on top.",
      "Refrigerate before serving.",
    ],
    prepTime: 5, cookTime: 15, servings: 12,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kesar Peda Mathura"),
  },
  {
    title: "Shrikhand", category: "dessert",
    description: "Maharashtra's luxurious strained yogurt dessert — thick, silky and fragrant with cardamom, saffron and pistachios.",
    ingredients: ["1 kg full-fat yogurt, hung overnight","¾ cup powdered sugar","½ tsp cardamom powder","A generous pinch of saffron in 2 tbsp warm milk","2 tbsp pistachios, slivered","2 tbsp almonds, slivered","1 tsp rose water"],
    instructions: [
      "Hang yogurt in muslin cloth overnight (8 hours) in the refrigerator — liquid whey drains away leaving thick chakka.",
      "Whisk the hung yogurt (chakka) until smooth and creamy.",
      "Add powdered sugar and whisk until dissolved.",
      "Add saffron milk, cardamom, and rose water. Mix.",
      "Fold in most of the pistachios and almonds.",
      "Refrigerate 2 hours.",
      "Serve chilled in small bowls garnished with remaining nuts.",
    ],
    prepTime: 480, cookTime: 0, servings: 6,
    cuisineType: "Maharashtrian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Shrikhand"),
  },
  {
    title: "Amrakhand", category: "dessert",
    description: "Mango shrikhand — Maharashtra's summer celebration in a bowl: hung yogurt whipped with Alphonso mango pulp and saffron.",
    ingredients: ["500g yogurt, hung overnight","¾ cup Alphonso mango pulp (or fresh mango)","½ cup powdered sugar","½ tsp cardamom powder","A pinch of saffron","Mango slices and pistachios for garnish"],
    instructions: [
      "Whisk hung yogurt until smooth.",
      "Add mango pulp, powdered sugar, cardamom, and saffron. Whisk together.",
      "Taste and adjust sweetness — ripe Alphonso mangoes add natural sweetness.",
      "Refrigerate at least 2 hours.",
      "Serve in small bowls with fresh mango slices and pistachios.",
    ],
    prepTime: 480, cookTime: 0, servings: 6,
    cuisineType: "Maharashtrian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Amrakhand Mango Shrikhand"),
  },
  {
    title: "Rabri", category: "dessert",
    description: "Slow-reduced thickened sweetened milk with layers of cream — eaten with jalebi, ladoos, or on its own as a chilled dessert.",
    ingredients: ["1 litre full-fat milk","½ cup sugar","½ tsp cardamom powder","A generous pinch of saffron","1 tsp rose water","2 tbsp pistachios and almonds, slivered"],
    instructions: [
      "Pour milk into a wide, heavy kadhai. Bring to a boil.",
      "Lower to medium heat. As cream forms on the surface, fold it to the sides of the pan (do not stir it back in).",
      "Keep collecting the cream layers on the sides as the milk reduces.",
      "Cook for 40–50 minutes until milk reduces to one-third.",
      "Add sugar, saffron, and cardamom. Stir gently.",
      "Scrape all the cream layers back into the milk.",
      "Add rose water. Cool. Refrigerate. Serve chilled with garnish.",
    ],
    prepTime: 5, cookTime: 55, servings: 6,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Rabri"),
  },
  {
    title: "Phirni", category: "dessert",
    description: "Creamy ground rice and milk pudding set in earthen bowls — subtly scented with rose and decorated with pistachios.",
    ingredients: ["3 tbsp basmati rice, soaked and ground to paste","1 litre full-fat milk","½ cup sugar","½ tsp cardamom powder","1 tsp rose water","A pinch of saffron","Pistachios and almonds for garnish"],
    instructions: [
      "Soak basmati rice for 30 minutes. Drain and grind with 2 tbsp milk to a smooth paste.",
      "Boil milk in a heavy pan. Add rice paste in a thin stream while stirring to prevent lumps.",
      "Cook on medium heat, stirring continuously, until it thickens noticeably — about 20 minutes.",
      "Add sugar, saffron, and cardamom. Cook 5 more minutes.",
      "Remove from heat. Add rose water.",
      "Pour into small earthen bowls (kulhads) or bowls. Refrigerate 3 hours until set.",
      "Serve chilled, decorated with pistachios.",
    ],
    prepTime: 40, cookTime: 30, servings: 6,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Phirni"),
  },
  // ── KULFI VARIETIES ──────────────────────────────────────────────────────────
  {
    title: "Malai Kulfi", category: "dessert",
    description: "Classic Indian frozen dessert — thickened condensed milk, cardamom and saffron frozen in conical moulds for that distinctive dense creamy texture.",
    ingredients: ["1 litre full-fat milk","½ cup condensed milk","½ cup sugar","½ tsp cardamom powder","A generous pinch of saffron","2 tbsp pistachios, slivered","1 tsp rose water","2 tbsp cornflour dissolved in 3 tbsp milk"],
    instructions: [
      "Boil milk in a heavy pan. Add cornflour mixture — stir quickly to prevent lumps.",
      "Add condensed milk, sugar, and saffron. Cook on medium heat, stirring, until reduced by half — 25 minutes.",
      "Cool to room temperature. Add cardamom, rose water and most of the pistachios.",
      "Pour into kulfi moulds or popsicle moulds. Insert sticks.",
      "Freeze overnight or for at least 8 hours.",
      "To serve, run the mould briefly under warm water and unmould.",
      "Garnish with slivered pistachios and serve immediately.",
    ],
    prepTime: 10, cookTime: 30, servings: 8,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Malai Kulfi"),
  },
  {
    title: "Mango Kulfi", category: "dessert",
    description: "Summer's greatest pleasure — Alphonso mango puree blended with thickened condensed milk and frozen to creamy perfection.",
    ingredients: ["1 cup Alphonso mango pulp","½ cup condensed milk","¾ cup heavy cream","¼ cup sugar (adjust)","½ tsp cardamom powder","1 tsp lime juice"],
    instructions: [
      "Whisk together mango pulp, condensed milk, cream, and sugar until smooth.",
      "Taste and adjust sweetness — ripe mangoes reduce sugar needed.",
      "Add cardamom and lime juice.",
      "Pour into kulfi moulds or popsicle moulds. Freeze overnight.",
      "Unmould by briefly running under warm water.",
      "Serve immediately with a slice of fresh mango.",
    ],
    prepTime: 10, cookTime: 5, servings: 6,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mango Kulfi"),
  },
  {
    title: "Pista Kulfi", category: "dessert",
    description: "Vivid green pistachio frozen dessert — intensely nutty and fragrant, the kulfi of choice at north Indian weddings.",
    ingredients: ["1 litre full-fat milk","½ cup condensed milk","¾ cup pistachios, soaked and peeled","½ cup sugar","½ tsp cardamom powder","Green food colour (optional)"],
    instructions: [
      "Peel soaked pistachios. Grind half into a paste, chop the rest.",
      "Reduce milk on medium heat with condensed milk for 20 minutes, stirring often.",
      "Add pistachio paste, sugar, and cardamom. Stir well.",
      "Cool completely. Fold in chopped pistachios.",
      "Pour into kulfi moulds and freeze overnight.",
      "Unmould and serve immediately.",
    ],
    prepTime: 70, cookTime: 25, servings: 8,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Pista Kulfi"),
  },
  // ── GHEVAR AND RAJASTHANI ────────────────────────────────────────────────────
  {
    title: "Ghevar", category: "dessert",
    description: "Rajasthan's Teej festival disc sweet — a crispy honeycomb lattice soaked in saffron syrup and layered with rabri.",
    ingredients: ["2 cups all-purpose flour","3 tbsp ghee","Ice cold water","Oil or ghee for deep frying","2 cups sugar","1 cup water","Saffron and cardamom","Rabri and pistachios for topping"],
    instructions: [
      "Mix flour, ghee, and enough ice cold water to form a thin, watery batter.",
      "Heat ghee in a cylindrical pan (a deep saucepan works). Drop batter in a thin stream into the centre.",
      "The batter will spread and create a lacy disc. Keep adding batter in stages.",
      "Fry until golden and crispy, rotating carefully.",
      "Prepare saffron sugar syrup. Soak ghevar in syrup briefly.",
      "Layer with chilled rabri. Garnish with pistachios and silver vark.",
      "Serve at room temperature.",
    ],
    prepTime: 20, cookTime: 30, servings: 4,
    cuisineType: "Rajasthani", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Ghevar Rajasthani"),
  },
  {
    title: "Churma Ladoo", category: "dessert",
    description: "Rajasthani coarse wheat ladoos made from baati (baked wheat balls) crushed with ghee and jaggery — rustic and deeply satisfying.",
    ingredients: ["2 cups whole wheat flour","½ cup ghee","¼ cup milk","Oil for deep frying","½ cup jaggery, grated","½ tsp cardamom powder","2 tbsp almonds and cashews"],
    instructions: [
      "Mix flour, ghee, and milk to a stiff dough. Divide into balls.",
      "Deep fry the balls on low heat until cooked through and golden — 15 minutes.",
      "Cool and crush coarsely in a mortar or food processor.",
      "Heat jaggery with 1 tbsp water until it melts.",
      "Mix crushed wheat with jaggery, remaining ghee, cardamom, and nuts.",
      "Shape into round ladoos while warm.",
      "Serve warm or at room temperature.",
    ],
    prepTime: 20, cookTime: 25, servings: 15,
    cuisineType: "Rajasthani", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Churma Ladoo Rajasthani"),
  },
  {
    title: "Gujiya", category: "dessert",
    description: "Holi's crowning delight — crescent-shaped deep-fried pastries filled with spiced khoya, coconut and dried fruit.",
    ingredients: ["2 cups all-purpose flour","4 tbsp ghee","Water to knead","1 cup khoya (mawa)","¼ cup grated coconut","¼ cup powdered sugar","2 tbsp raisins","2 tbsp cashews","½ tsp cardamom powder","Oil for frying","Sugar syrup for coating"],
    instructions: [
      "Rub ghee into flour until crumbly. Add water gradually to form a stiff dough. Rest 30 minutes.",
      "For filling: crumble and roast khoya in a pan for 5 minutes. Cool. Mix with coconut, sugar, raisins, cashews, and cardamom.",
      "Roll dough thin. Cut into circles using a cutter.",
      "Place filling on one half. Fold and crimp the edges using a fork or gujiya mould.",
      "Deep fry on medium-low heat until golden all over — 8 minutes.",
      "Dip in sugar syrup if desired. Drain on paper.",
      "Store in an airtight container for up to 1 week.",
    ],
    prepTime: 45, cookTime: 30, servings: 20,
    cuisineType: "North Indian", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Gujiya Holi sweet"),
  },
  // ── SOUTH INDIAN SWEETS ──────────────────────────────────────────────────────
  {
    title: "Ada Pradhaman", category: "dessert",
    description: "Kerala Onam's royal payasam — rice ada (flat rice flakes) cooked in coconut milk and jaggery with fried coconut and cashews.",
    ingredients: ["100g rice ada","2 cups jaggery","1½ cups thick coconut milk","2 cups thin coconut milk","3 tbsp ghee","¼ cup cashews","¼ cup sliced coconut","A pinch of cardamom and dry ginger powder"],
    instructions: [
      "Boil ada in water until soft (about 20 minutes). Drain and set aside.",
      "Dissolve jaggery in 1 cup warm water. Strain and bring to a boil.",
      "Add cooked ada to jaggery. Stir and cook 10 minutes until thick.",
      "Add thin coconut milk and cook 5 more minutes.",
      "Lower heat. Add thick coconut milk — do NOT boil after this.",
      "Stir in cardamom and dry ginger.",
      "Fry cashews and coconut in ghee until golden. Pour over payasam.",
    ],
    prepTime: 25, cookTime: 40, servings: 8,
    cuisineType: "South Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Ada Pradhaman Onam"),
  },
  {
    title: "Unniyappam", category: "dessert",
    description: "Small round Kerala fried rice balls sweet with banana and jaggery — made in an appam pan and offered at temples.",
    ingredients: ["1 cup rice flour","2 ripe bananas, mashed","½ cup jaggery, dissolved","¼ cup coconut, grated","1 tsp sesame seeds","½ tsp cardamom powder","A pinch of baking powder","Coconut oil for frying"],
    instructions: [
      "Dissolve jaggery in ¼ cup warm water. Strain.",
      "Mix rice flour, mashed banana, jaggery syrup, coconut, sesame, cardamom, and baking powder to a thick batter.",
      "Rest 30 minutes.",
      "Heat an appam/appe pan (or muffin tin). Add a few drops of coconut oil into each cavity.",
      "Pour batter into each cavity — fill ¾ full.",
      "Cook on medium heat. When the edges set, flip each one using a skewer.",
      "Cook until dark golden brown and cooked through.",
    ],
    prepTime: 35, cookTime: 20, servings: 20,
    cuisineType: "South Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Unniyappam Kerala"),
  },
  {
    title: "Modak", category: "dessert",
    description: "Ganesh's beloved steamed sweet dumpling — rice flour shells filled with jaggery-coconut-cardamom stuffing. Essential for Ganesh Chaturthi.",
    ingredients: ["1 cup rice flour","1 cup boiling water","A pinch of salt","1 tsp ghee","For filling: 1 cup fresh grated coconut","¾ cup jaggery","½ tsp cardamom powder","1 tbsp sesame seeds (optional)"],
    instructions: [
      "Make filling: cook coconut and jaggery in a pan until jaggery melts and mixture comes together. Add cardamom. Cool.",
      "Pour boiling water and salt over rice flour. Mix quickly with a spoon, then knead with greased hands to smooth dough.",
      "Divide into balls. Flatten each ball into a cup shape using wet hands.",
      "Place a spoon of filling in the centre. Pleat and seal the top into a cone shape.",
      "Steam the modaks for 10–12 minutes until translucent.",
      "Brush with ghee and serve warm with a drizzle of ghee.",
    ],
    prepTime: 25, cookTime: 20, servings: 12,
    cuisineType: "Maharashtrian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Ukadiche Modak Ganesh Chaturthi"),
  },
  {
    title: "Fried Modak", category: "dessert",
    description: "Crispy deep-fried version of the beloved modak — golden crescent-shaped pastry filled with coconut-jaggery for Ganesh Chaturthi.",
    ingredients: ["1 cup all-purpose flour","1 tbsp ghee","Water to knead","1 cup fresh coconut, grated","¾ cup jaggery","½ tsp cardamom powder","Oil for frying"],
    instructions: [
      "Rub ghee into flour until crumbly. Add water to form a medium-stiff dough. Rest 20 minutes.",
      "Make filling: cook coconut with jaggery until thick. Add cardamom. Cool.",
      "Roll dough thin. Cut into circles.",
      "Fill with coconut mixture. Fold into half-moon and seal edges by pleating or pressing with a fork.",
      "Deep fry on medium heat until golden all over.",
      "Drain on paper and serve warm or at room temperature.",
    ],
    prepTime: 30, cookTime: 20, servings: 15,
    cuisineType: "Maharashtrian", dietaryTags: ["Vegan"],
    imageUrl: null, youtubeUrl: yt("Fried Modak"),
  },
  {
    title: "Paal Payasam", category: "dessert",
    description: "Tamil Nadu's beloved plain milk rice pudding — rice slow-cooked in whole milk for hours until thick, creamy and naturally sweet.",
    ingredients: ["¼ cup raw rice (sona masuri or gobindobhog)","2 litres full-fat milk","¾ cup sugar","½ tsp cardamom powder","A generous pinch of saffron","2 tbsp ghee","2 tbsp cashews and raisins"],
    instructions: [
      "Fry cashews and raisins in ghee. Set aside.",
      "Boil milk in a heavy pot. Add washed rice.",
      "Cook on medium-low heat for 45–60 minutes, stirring frequently, until rice is completely cooked and milk has reduced to thick consistency.",
      "Add sugar, saffron, and cardamom. Stir well and cook 10 more minutes.",
      "The payasam should coat a spoon thickly.",
      "Add fried cashews and raisins.",
      "Serve warm or chilled — both are equally delicious.",
    ],
    prepTime: 5, cookTime: 70, servings: 8,
    cuisineType: "South Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Paal Payasam Rice Milk"),
  },
  {
    title: "Sweet Pongal", category: "dessert",
    description: "Chakkarai Pongal — Tamil Nadu's sacred harvest festival sweet of rice and split moong dal cooked with jaggery, ghee and cashews.",
    ingredients: ["½ cup raw rice","¼ cup yellow moong dal","¾ cup jaggery","3 tbsp ghee","2 cups water","1½ cups milk","½ tsp cardamom powder","A pinch of nutmeg","2 tbsp cashews","2 tbsp raisins","A few edible camphor flakes (optional)"],
    instructions: [
      "Dry roast moong dal for 2 minutes. Cook rice and dal together with water and milk in a pressure cooker for 3 whistles.",
      "Mash the cooked mixture well.",
      "Dissolve jaggery in ½ cup warm water. Strain.",
      "Cook the rice-dal mixture with jaggery syrup on medium heat, stirring until thick — 10 minutes.",
      "Add ghee, cardamom, and nutmeg.",
      "Fry cashews and raisins in ghee and add.",
      "Serve warm with an extra drizzle of ghee.",
    ],
    prepTime: 10, cookTime: 30, servings: 6,
    cuisineType: "South Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Sweet Pongal Chakkarai"),
  },
  {
    title: "Kozhukattai", category: "dessert",
    description: "Steamed rice flour dumplings from Tamil Nadu with sesame-jaggery filling — beautiful triangular or sphere-shaped temple prasad.",
    ingredients: ["1 cup rice flour","1 cup boiling water","Salt and ghee","For filling: ½ cup black sesame seeds","½ cup jaggery","¼ cup grated coconut","½ tsp cardamom"],
    instructions: [
      "Make filling: roast sesame seeds, grind coarsely. Mix with melted jaggery, coconut and cardamom.",
      "Pour boiling water over rice flour with salt. Mix with ghee and knead to smooth pliable dough.",
      "Take a portion, flatten it in your palm, place filling inside and shape into a triangle or ball.",
      "Steam for 10–12 minutes until the dough turns translucent.",
      "Serve warm with a little ghee drizzled on top.",
    ],
    prepTime: 20, cookTime: 20, servings: 12,
    cuisineType: "South Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kozhukattai Tamil"),
  },
  {
    title: "Chakka Pradhaman", category: "dessert",
    description: "Jackfruit payasam from Kerala — ripe jackfruit cooked with coconut milk and jaggery, fragrant with cardamom and dry ginger.",
    ingredients: ["1 cup ripe jackfruit (fresh or canned), mashed","1 cup jaggery","2 cups coconut milk (thin)","1 cup coconut milk (thick)","2 tbsp ghee","¼ cup cashews","¼ cup sliced coconut","½ tsp cardamom powder","A pinch of dry ginger"],
    instructions: [
      "Cook jackfruit pulp in a pan on low heat until soft.",
      "Add jaggery and cook, stirring, until jaggery melts and mixture thickens — 15 minutes.",
      "Add thin coconut milk. Cook on medium heat for 10 more minutes.",
      "Lower heat. Add thick coconut milk — stir gently, do not boil.",
      "Add cardamom and dry ginger.",
      "Fry cashews and sliced coconut in ghee until golden. Pour over payasam.",
      "Serve warm or at room temperature.",
    ],
    prepTime: 20, cookTime: 35, servings: 6,
    cuisineType: "South Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Chakka Pradhaman Jackfruit Payasam"),
  },
  {
    title: "Elaneer Payasam", category: "dessert",
    description: "Tender coconut pudding — soft coconut jelly pieces in sweetened thickened milk with saffron. Light and cooling.",
    ingredients: ["2 tender coconuts (water and jelly)","1 litre full-fat milk","½ cup sugar","½ tsp cardamom powder","A pinch of saffron"],
    instructions: [
      "Collect the tender coconut water. Scrape out the soft jelly from inside.",
      "Boil milk and reduce by one-third, stirring often.",
      "Add sugar, saffron, and cardamom.",
      "Pour in coconut water. Gently add coconut jelly pieces.",
      "Cook very gently on low heat for 5 minutes — don't overcook the jelly.",
      "Chill and serve cold.",
    ],
    prepTime: 20, cookTime: 25, servings: 4,
    cuisineType: "South Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Elaneer Payasam Tender Coconut"),
  },
  // ── GUJARATI SWEETS ──────────────────────────────────────────────────────────
  {
    title: "Mohanthal", category: "dessert",
    description: "Gujarat's beloved chickpea flour fudge — coarse, nutty and richly flavoured, given as prasad at the Dwarkadhish temple.",
    ingredients: ["2 cups coarse besan (chickpea flour)","¾ cup ghee","1 cup sugar","½ cup water","½ tsp cardamom powder","A pinch of saffron","¼ cup milk","2 tbsp pistachios and almonds"],
    instructions: [
      "Mix besan with 2 tbsp warm ghee and enough milk to make a crumbly mixture. Sieve through a coarse sieve.",
      "Heat remaining ghee in a heavy pan. Add the crumbly besan and roast on low heat, stirring continuously for 25–30 minutes until golden and fragrant.",
      "Prepare sugar syrup to one-string consistency with saffron.",
      "Remove besan from heat. Pour syrup over immediately. Add cardamom. Mix quickly.",
      "Pour into a greased plate. Smooth the top. Press nuts on top.",
      "Cool completely. Cut into diamond shapes.",
    ],
    prepTime: 10, cookTime: 40, servings: 20,
    cuisineType: "Gujarati", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mohanthal Gujarati"),
  },
  {
    title: "Sukhdi", category: "dessert",
    description: "Gudpapdi — Gujarat's simplest winter sweet: whole wheat flour roasted in ghee with jaggery, eaten warm as an energy food.",
    ingredients: ["1 cup whole wheat flour","½ cup ghee","½ cup jaggery, grated","½ tsp cardamom powder","2 tbsp sesame seeds (optional)"],
    instructions: [
      "Heat ghee in a heavy pan. Add wheat flour.",
      "Roast on medium-low heat, stirring continuously for 15–20 minutes until golden and fragrant.",
      "Remove from heat. Cool slightly.",
      "Add jaggery and cardamom. Mix quickly — jaggery will melt from the residual heat.",
      "Add sesame seeds if using. Mix well.",
      "Pour onto greased plate while still liquid. Spread evenly.",
      "Cut into squares while warm. Cool completely before removing from plate.",
    ],
    prepTime: 5, cookTime: 25, servings: 15,
    cuisineType: "Gujarati", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Sukhdi Gudpapdi Gujarati"),
  },
  {
    title: "Kopra Pak", category: "dessert",
    description: "Dry desiccated coconut fudge from Gujarat — three-layered (white, yellow, green) coconut sweet that's Diwali box essential.",
    ingredients: ["3 cups desiccated coconut","1 cup sugar","¼ cup water","3 tbsp ghee","½ tsp cardamom","Food colour (yellow and green for layers)","½ tsp rose water"],
    instructions: [
      "Cook sugar and water to one-string syrup. Add ghee.",
      "Divide syrup into three portions.",
      "Mix 1 cup coconut into each portion. Add white, yellow, and green colour respectively.",
      "Cook each portion for 5 minutes separately until thick.",
      "Grease a plate. Layer white, then yellow, then green coconut mixture.",
      "Press firmly. Cool and cut into small squares.",
    ],
    prepTime: 15, cookTime: 20, servings: 25,
    cuisineType: "Gujarati", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kopra Pak Gujarati coconut sweet"),
  },
  // ── SAVOURY SNACKS ───────────────────────────────────────────────────────────
  {
    title: "Chakli", category: "dessert",
    description: "Crispy coiled spiral savoury snack from Maharashtra — made from rice and urad dal flour, deep fried until perfectly crunchy.",
    ingredients: ["2 cups rice flour","¼ cup urad dal flour","2 tbsp ghee","1 tsp cumin seeds","1 tsp sesame seeds","½ tsp turmeric","½ tsp red chilli powder","Salt to taste","Water to knead","Oil for frying"],
    instructions: [
      "Mix all flours with ghee, cumin, sesame, turmeric, chilli, and salt.",
      "Add hot water gradually to make a medium-stiff dough.",
      "Fill a chakli press with the dough. Pipe spirals onto parchment or directly into hot oil.",
      "Fry on medium-low heat for 3–4 minutes per side until golden and crispy.",
      "Drain on paper. Cool completely before storing.",
      "Store in an airtight container — stays crispy for 2 weeks.",
    ],
    prepTime: 20, cookTime: 30, servings: 30,
    cuisineType: "Maharashtrian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Chakli recipe"),
  },
  {
    title: "Murukku", category: "dessert",
    description: "Tamil Nadu's iconic crunchy sesame rice spirals — a must for Diwali and Krishnashtami, equally beloved as a tea-time snack.",
    ingredients: ["2 cups rice flour","¼ cup urad dal flour, roasted","1 tbsp sesame seeds","1 tbsp butter","½ tsp cumin powder","½ tsp asafoetida","Salt to taste","Water to knead","Oil for frying"],
    instructions: [
      "Mix rice flour, urad flour, sesame seeds, butter, cumin, asafoetida, and salt.",
      "Add water gradually and knead to a smooth, medium-stiff dough.",
      "Fill a murukku press with the star disc attachment.",
      "Press spirals directly into hot oil (170°C).",
      "Fry on medium heat, turning once, until golden and the sizzling slows — about 4 minutes.",
      "Drain and cool completely. Store in airtight container.",
    ],
    prepTime: 20, cookTime: 30, servings: 30,
    cuisineType: "South Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Murukku recipe"),
  },
  {
    title: "Peanut Chikki", category: "dessert",
    description: "Crunchy peanut brittle with jaggery — the ultimate quick Indian sweet, made in minutes and lasting weeks.",
    ingredients: ["2 cups roasted peanuts, skinned","1 cup jaggery, grated","2 tbsp water","1 tsp ghee"],
    instructions: [
      "Grease a plate or baking sheet with ghee.",
      "Cook jaggery with water in a heavy pan, stirring until it reaches hard crack stage — test: a drop in cold water should snap sharply.",
      "Quickly stir in roasted peanuts.",
      "Pour onto the greased plate immediately.",
      "Spread with a greased spatula or rolling pin to ½ cm thickness.",
      "Score into pieces while still warm. Cool completely.",
      "Break along scored lines. Store in airtight jar.",
    ],
    prepTime: 10, cookTime: 15, servings: 20,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Peanut Chikki Jaggery"),
  },
  {
    title: "Sesame Chikki", category: "dessert",
    description: "Til ki chikki — toasted sesame seed brittle with jaggery, thin and snappy. Essential at Lohri and Makar Sankranti.",
    ingredients: ["2 cups white sesame seeds","1 cup jaggery","2 tbsp water","1 tsp ghee"],
    instructions: [
      "Dry roast sesame seeds on low heat until they splutter and turn golden. Cool.",
      "Melt jaggery with water to hard crack stage (test in cold water).",
      "Add toasted sesame seeds quickly. Stir.",
      "Pour onto a greased surface immediately. Spread paper thin using a greased rolling pin.",
      "Score into rectangles while soft. Cool completely.",
      "Break along scored lines. The chikki should be translucent and snappy.",
    ],
    prepTime: 10, cookTime: 15, servings: 20,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Til Chikki Sesame Brittle"),
  },
  {
    title: "Mathri", category: "dessert",
    description: "Flaky, buttery savoury crackers from North India — seasoned with ajwain, black pepper and cumin. Perfect with pickle and chai.",
    ingredients: ["2 cups all-purpose flour","½ cup ghee","1 tsp ajwain (carom seeds)","1 tsp black pepper, coarsely crushed","½ tsp cumin seeds","Salt to taste","Water to knead","Oil for frying"],
    instructions: [
      "Rub ghee into flour until it resembles breadcrumbs.",
      "Add ajwain, black pepper, cumin, and salt. Mix.",
      "Add cold water gradually to form a stiff dough. Do NOT over-knead.",
      "Rest 20 minutes.",
      "Roll small portions into thin circles (3mm thick). Prick all over with a fork.",
      "Deep fry on low-medium heat until golden and crispy — about 5 minutes.",
      "Drain and cool. Store in airtight tin for up to 2 weeks.",
    ],
    prepTime: 25, cookTime: 25, servings: 20,
    cuisineType: "North Indian", dietaryTags: ["Vegan"],
    imageUrl: null, youtubeUrl: yt("Mathri recipe"),
  },
  {
    title: "Namak Pare", category: "dessert",
    description: "Diamond-shaped crispy savoury crackers — lightly seasoned, perfectly golden and impossible to stop eating.",
    ingredients: ["2 cups all-purpose flour","3 tbsp ghee","1 tsp ajwain","½ tsp black pepper","Salt to taste","Water to knead","Oil for deep frying"],
    instructions: [
      "Rub ghee into flour. Add ajwain, pepper, and salt.",
      "Add water to make a medium-stiff dough. Rest 20 minutes.",
      "Roll thin (2–3mm). Cut into diamond shapes using a knife.",
      "Deep fry on low-medium heat until light golden — 4–5 minutes.",
      "Drain and cool completely. They crisp up more as they cool.",
      "Store in airtight container for 2 weeks.",
    ],
    prepTime: 25, cookTime: 25, servings: 25,
    cuisineType: "North Indian", dietaryTags: ["Vegan"],
    imageUrl: null, youtubeUrl: yt("Namak Pare recipe"),
  },
  {
    title: "Shakarpare", category: "dessert",
    description: "Sweet diamond-shaped fried pastry — lightly sweet with a crispy bite, a Diwali must-have across North India.",
    ingredients: ["2 cups all-purpose flour","3 tbsp ghee","½ cup powdered sugar","½ tsp cardamom powder","Milk to knead","Oil for frying"],
    instructions: [
      "Rub ghee into flour. Add powdered sugar and cardamom.",
      "Add milk gradually to form a stiff dough. Do not over-knead.",
      "Roll to 3mm thickness. Cut into diamond shapes.",
      "Deep fry on low-medium heat until light golden — they should NOT be dark.",
      "Cool completely — they harden as they cool.",
      "Store in airtight tin for 2 weeks.",
    ],
    prepTime: 20, cookTime: 20, servings: 25,
    cuisineType: "North Indian", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Shakarpare Diwali"),
  },
  // ── BENGALI / EAST INDIAN ────────────────────────────────────────────────────
  {
    title: "Patishapta", category: "dessert",
    description: "Bengali thin rice crepes rolled with coconut and nolen gur filling — a winter Makar Sankranti festival delight.",
    ingredients: ["1 cup rice flour","¼ cup all-purpose flour","¼ cup semolina","2 cups milk","1 tbsp sugar","Ghee for cooking","For filling: 2 cups grated coconut","1 cup nolen gur (or jaggery)","½ tsp cardamom"],
    instructions: [
      "Make filling: cook grated coconut with jaggery on low heat until it comes together. Add cardamom. Cool.",
      "Mix rice flour, plain flour, semolina, milk, and sugar to a smooth, thin, flowing batter.",
      "Heat a flat pan and brush with ghee. Pour a thin ladleful of batter.",
      "Spread into a thin circle (like a crepe). Cook 1 minute until set.",
      "Place a line of coconut filling in the centre. Roll the crepe around it.",
      "Repeat with remaining batter.",
      "Serve warm drizzled with a little extra jaggery.",
    ],
    prepTime: 20, cookTime: 25, servings: 12,
    cuisineType: "Bengali", dietaryTags: ["Vegan"],
    imageUrl: null, youtubeUrl: yt("Patishapta Bengali crepe"),
  },
  {
    title: "Misti Polao", category: "dessert",
    description: "Bengali sweet saffron rice — lightly sweetened basmati cooked with raisins and cashews, served on festive occasions.",
    ingredients: ["2 cups basmati rice","½ cup sugar","3 tbsp ghee","¼ cup raisins","¼ cup cashews","½ tsp cardamom powder","A generous pinch of saffron","3½ cups water"],
    instructions: [
      "Soak basmati rice 30 minutes. Drain.",
      "Heat ghee in a heavy pot. Fry cashews until golden. Remove.",
      "Add raisins and fry briefly. Remove.",
      "Add sugar to the same ghee. Cook until it caramelises to a light golden colour.",
      "Add rice and stir to coat with caramel.",
      "Add water, saffron, and cardamom. Bring to a boil.",
      "Cover and cook on lowest heat for 12 minutes. Fluff. Serve with cashews and raisins.",
    ],
    prepTime: 35, cookTime: 20, servings: 6,
    cuisineType: "Bengali", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Misti Polao Bengali Sweet Rice"),
  },
  // ── NORTH INDIAN OTHERS ──────────────────────────────────────────────────────
  {
    title: "Pinni", category: "dessert",
    description: "Punjab's warming winter sweet — whole wheat flour and edible gum roasted in ghee with jaggery, nuts and dried coconut.",
    ingredients: ["2 cups whole wheat flour","3 tbsp edible gum (gond)","½ cup ghee","½ cup jaggery, grated","¼ cup almonds, chopped","¼ cup cashews, chopped","2 tbsp dried coconut","½ tsp cardamom powder","2 tbsp dry ginger powder"],
    instructions: [
      "Fry edible gum in ghee until it puffs up like popcorn. Remove and crush lightly.",
      "In the same ghee, roast flour on low heat for 20–25 minutes until golden and nutty.",
      "Remove from heat. Cool slightly.",
      "Melt jaggery with 2 tbsp water. Pour over flour. Add gond, nuts, coconut, cardamom, and dry ginger.",
      "Mix well. Shape into medium balls while warm.",
      "Allow to cool and harden. Keeps for 2 weeks in airtight container.",
    ],
    prepTime: 15, cookTime: 30, servings: 20,
    cuisineType: "Punjabi", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Pinni Punjabi winter sweet"),
  },
  {
    title: "Balushahi", category: "dessert",
    description: "Honey-dipped, flaky deep-fried pastry discs — lighter than a donut and more complex than a barfi. A North Indian wedding essential.",
    ingredients: ["2 cups all-purpose flour","½ cup ghee","¼ cup yogurt","A pinch of baking soda","Oil for frying","2 cups sugar","1 cup water","Saffron and cardamom for syrup","Pistachios for garnish"],
    instructions: [
      "Rub ghee into flour until crumbly. Add baking soda.",
      "Add yogurt and mix gently. Add a little water if needed to bring dough together — it should be soft and flaky.",
      "Rest 30 minutes.",
      "Divide into round balls. Flatten into discs. Press thumb in the centre of each.",
      "Deep fry on very low heat (don't rush!) for 12–15 minutes until golden and cooked through.",
      "Drain. Dip in warm sugar syrup for 2 minutes.",
      "Remove. Sprinkle with pistachios. Allow syrup to set.",
    ],
    prepTime: 35, cookTime: 25, servings: 15,
    cuisineType: "North Indian", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Balushahi recipe"),
  },
  {
    title: "Petha", category: "dessert",
    description: "Agra's crystalline translucent white gourd sweet — soft, chewy and soaked in fragrant sugar syrup. Agra's most famous export.",
    ingredients: ["1 kg ash gourd (white pumpkin)","2 cups sugar","1 cup water","½ tsp citric acid (or alum)","½ tsp cardamom powder","Saffron strands","Rose water"],
    instructions: [
      "Peel and cut ash gourd into blocks. Pierce all over with a fork.",
      "Soak in alum water for 30 minutes to firm the texture.",
      "Rinse and par-boil until just tender but still holding shape.",
      "Prepare sugar syrup. Add gourd pieces and cook on low heat for 30 minutes until translucent.",
      "Add cardamom, saffron, and rose water.",
      "Cook until the pieces absorb most of the syrup and turn glossy.",
      "Cool and serve. The petha should be slightly sticky and translucent.",
    ],
    prepTime: 60, cookTime: 45, servings: 12,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Agra Petha recipe"),
  },
  {
    title: "Imarti", category: "dessert",
    description: "Urad dal spirals deep-fried and soaked in saffron syrup — crispier and denser than jalebi, with a characteristic slightly sticky exterior.",
    ingredients: ["1 cup urad dal, soaked 4 hours","Oil for frying","1½ cups sugar","¾ cup water","½ tsp cardamom","Saffron strands","Orange food colour (optional)"],
    instructions: [
      "Grind soaked dal with very little water to a thick, smooth, fluffy batter.",
      "Add colour and mix. The batter should be thick enough to hold a spiral shape.",
      "Make sugar syrup to one-string consistency. Add saffron and cardamom.",
      "Fill batter into a piping bag or squeeze bottle with a small round nozzle.",
      "Heat oil to 160°C. Pipe concentric spirals into the oil.",
      "Fry until golden, turning once — 3 minutes per side.",
      "Soak in warm syrup for 2 minutes. Serve warm.",
    ],
    prepTime: 240, cookTime: 30, servings: 12,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Imarti recipe"),
  },
  {
    title: "Sohan Halwa", category: "dessert",
    description: "Dense, toffee-like Punjab halwa made with wheat starch, sugar and ghee — chewy and rich, a winter speciality.",
    ingredients: ["1 cup cornflour or wheat starch","3 cups sugar","2 cups water","½ cup ghee","½ tsp cardamom","A pinch of saffron","¼ cup almonds, pistachios, and cashews"],
    instructions: [
      "Dissolve cornflour in 1 cup cold water until smooth.",
      "Cook sugar and remaining water to a thick syrup.",
      "Slowly add cornflour mixture to syrup, stirring vigorously over medium heat.",
      "Add ghee in batches, stirring continuously until the halwa is very thick and pulls away from the pan — 25 minutes.",
      "Add saffron and cardamom.",
      "Pour into a greased plate. Top with nuts. Cool and cut into pieces.",
    ],
    prepTime: 10, cookTime: 35, servings: 15,
    cuisineType: "Punjabi", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Sohan Halwa Punjab"),
  },
  // ── FALOODA AND PAN-INDIAN ────────────────────────────────────────────────────
  {
    title: "Falooda", category: "dessert",
    description: "Mumbai's iconic layered rose-milk dessert drink — falooda noodles, basil seeds, rose syrup, milk, and ice cream in a tall glass.",
    ingredients: ["¼ cup falooda sev (thin vermicelli)","2 tbsp sabja (basil/tukmaria seeds), soaked","3 tbsp rose syrup","1 cup cold milk","2 scoops vanilla or rose ice cream","1 tsp cornflour","Red/pink jelly (optional)"],
    instructions: [
      "Cook falooda sev in boiling water for 2 minutes. Drain and cool in cold water.",
      "Soak sabja seeds in water for 20 minutes until they bloom.",
      "Dissolve cornflour in 2 tbsp cold milk. Heat remaining milk and add cornflour mixture. Stir until slightly thickened. Cool.",
      "In a tall glass: add rose syrup, then falooda sev, then soaked sabja seeds.",
      "Pour cold milk over gently.",
      "Top with ice cream scoops.",
      "Drizzle more rose syrup. Serve immediately with a long spoon and straw.",
    ],
    prepTime: 25, cookTime: 5, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Falooda recipe"),
  },
  {
    title: "Kulfi Falooda", category: "dessert",
    description: "The ultimate Indian street dessert — creamy pistachio kulfi over rose falooda noodles, sabja seeds and rose syrup.",
    ingredients: ["1 kulfi (malai or pista, sliced)","¼ cup falooda sev, cooked","2 tbsp sabja seeds, soaked","3 tbsp rose syrup","1 cup cold milk","Chopped pistachios for garnish"],
    instructions: [
      "Cook falooda sev per packet instructions. Drain and cool.",
      "Soak sabja seeds until bloomed.",
      "In a deep bowl or glass: pour rose syrup first.",
      "Add falooda noodles and sabja seeds.",
      "Pour cold milk.",
      "Place sliced kulfi on top.",
      "Sprinkle with chopped pistachios. Serve immediately.",
    ],
    prepTime: 15, cookTime: 5, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kulfi Falooda"),
  },
  {
    title: "Thekua", category: "dessert",
    description: "Bihar's sacred Chhath Puja offering — hard, dry wheat cookies fried in ghee, sweetened with jaggery and fragrant with anise.",
    ingredients: ["2 cups whole wheat flour","½ cup jaggery, grated","3 tbsp ghee","1 tsp fennel seeds","½ tsp cardamom","¼ cup desiccated coconut","Milk to bind","Oil for frying"],
    instructions: [
      "Dissolve jaggery in 3 tbsp warm water.",
      "Mix flour with ghee until crumbly. Add jaggery, fennel seeds, cardamom, and coconut.",
      "Add milk gradually to form a stiff dough.",
      "Press into a thekua mould or roll and cut into small ovals.",
      "Deep fry on medium-low heat until dark golden and hard — about 8 minutes.",
      "Drain and cool completely — they harden more as they cool.",
      "Store in airtight container for 2 weeks.",
    ],
    prepTime: 20, cookTime: 25, servings: 20,
    cuisineType: "East Indian", dietaryTags: ["Vegan"],
    imageUrl: null, youtubeUrl: yt("Thekua Chhath Puja"),
  },
  {
    title: "Anarsa", category: "dessert",
    description: "Maharashtrian Diwali rice cookie — soaked rice ground with jaggery, fried in ghee and rolled in poppy seeds.",
    ingredients: ["2 cups rice, soaked 3 days and dried","1 cup jaggery, grated","½ cup poppy seeds (khus khus)","Oil or ghee for frying"],
    instructions: [
      "Soak rice for 3 days, changing water daily. Dry completely and grind to fine flour.",
      "Knead rice flour with jaggery (no water needed — jaggery provides moisture). Knead to a stiff dough.",
      "Divide into small balls. Press into small flat discs.",
      "Press one side into poppy seeds — poppy seeds should coat one side.",
      "Fry poppy seed side down first on low-medium heat until golden. Flip and fry the other side.",
      "Drain on paper. Cool completely — they crisp up beautifully.",
    ],
    prepTime: 4320, cookTime: 25, servings: 20,
    cuisineType: "Maharashtrian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Anarsa Diwali recipe"),
  },
  {
    title: "Karanji", category: "dessert",
    description: "Maharashtrian gujiya — crescent pastry with coconut-semolina-jaggery filling, deep fried to golden crispiness for Diwali.",
    ingredients: ["2 cups all-purpose flour","3 tbsp ghee","Water to knead","For filling: 1 cup desiccated coconut","½ cup semolina, dry roasted","½ cup powdered sugar","½ tsp cardamom","2 tbsp raisins","Oil for frying"],
    instructions: [
      "Rub ghee into flour. Add water to form a stiff dough. Rest 30 minutes.",
      "Mix all filling ingredients together.",
      "Roll dough thin. Cut into circles.",
      "Fill with coconut mixture. Fold and crimp edges.",
      "Deep fry on medium-low heat until golden all over — 8 minutes.",
      "Drain and cool. Store in airtight container up to 1 week.",
    ],
    prepTime: 40, cookTime: 30, servings: 20,
    cuisineType: "Maharashtrian", dietaryTags: ["Vegan"],
    imageUrl: null, youtubeUrl: yt("Karanji Maharashtrian Diwali"),
  },
  {
    title: "Rava Kesari", category: "dessert",
    description: "Karnataka's sunny orange semolina sweet — quick to make, fragrant with saffron and cardamom. Temple prasad and home favourite.",
    ingredients: ["1 cup fine semolina (rava)","2½ cups water","¾ cup sugar","3 tbsp ghee","½ tsp cardamom powder","A generous pinch of saffron in 2 tbsp warm water","2 tbsp cashews","2 tbsp raisins","A few drops of orange food colour (optional)"],
    instructions: [
      "Heat ghee. Fry cashews and raisins until golden. Remove.",
      "In the same ghee, roast semolina on medium heat for 5 minutes until lightly golden.",
      "Boil water with colour and saffron. Slowly pour over roasted rava while stirring vigorously to prevent lumps.",
      "Cook on medium heat, stirring, until rava absorbs all water.",
      "Add sugar. Stir quickly as mixture thickens.",
      "Add cardamom. Cook 3 more minutes until the kesari leaves the pan sides.",
      "Garnish with fried cashews and raisins. Serve hot.",
    ],
    prepTime: 5, cookTime: 15, servings: 6,
    cuisineType: "South Indian", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Rava Kesari"),
  },
  {
    title: "Panchamrit", category: "dessert",
    description: "Sacred temple prasad — the five-nectar mixture of milk, yogurt, honey, ghee and sugar, offered to the deity and served to devotees.",
    ingredients: ["½ cup full-fat milk","½ cup yogurt","2 tbsp honey","1 tsp ghee","2 tbsp sugar","A pinch of cardamom","Tulsi leaves"],
    instructions: [
      "Combine milk and yogurt in a small bowl.",
      "Add honey, ghee, and sugar. Stir gently until sugar dissolves.",
      "Add a tiny pinch of cardamom powder.",
      "Traditionally offered to the deity first, then distributed as prasad.",
      "Serve in small portions — this is very sweet and rich.",
      "Always prepare fresh. Do not refrigerate as it's meant to be consumed immediately.",
    ],
    prepTime: 5, cookTime: 0, servings: 6,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Panchamrit prasad recipe"),
  },
  {
    title: "Anjeer Barfi", category: "dessert",
    description: "Fig and milk fudge — naturally sweet dried figs blended with milk solids and nuts. A nutritious festive sweet.",
    ingredients: ["1 cup dried figs (anjeer)","½ cup milk","½ cup khoya","¼ cup powdered sugar","½ tsp cardamom","2 tbsp almonds, pistachios","1 tbsp ghee"],
    instructions: [
      "Soak dried figs in warm milk for 30 minutes until soft.",
      "Blend with soaking milk to a smooth paste.",
      "Heat ghee in a pan. Cook fig paste on medium heat, stirring for 5 minutes.",
      "Add khoya and powdered sugar. Stir for 10 more minutes until thick.",
      "Add cardamom and nuts. Mix.",
      "Pour into greased plate. Press nuts on top. Cool and cut into pieces.",
    ],
    prepTime: 35, cookTime: 20, servings: 15,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Anjeer Barfi Fig"),
  },
  {
    title: "Khajoor Barfi", category: "dessert",
    description: "Dates and nut fudge — no-cook, naturally sweetened with medjool dates, rich with cashews and coconut. Healthy festival sweet.",
    ingredients: ["2 cups medjool dates, pitted","1 cup cashews","½ cup desiccated coconut","¼ cup almonds","½ tsp cardamom powder","1 tsp ghee","Pistachios for garnish"],
    instructions: [
      "Soak dates in warm water for 10 minutes if hard. Drain.",
      "Process dates in a food processor to a sticky paste.",
      "Coarsely grind cashews and almonds.",
      "Mix date paste, nuts, coconut, and cardamom together with ghee.",
      "Press into a greased dish. Press pistachios on top.",
      "Refrigerate 2 hours. Cut into squares or roll into balls.",
      "Store refrigerated for up to 2 weeks.",
    ],
    prepTime: 20, cookTime: 0, servings: 20,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Khajoor Barfi Dates"),
  },
  // ── MAWA KACHORI AND MORE ─────────────────────────────────────────────────────
  {
    title: "Mawa Kachori", category: "dessert",
    description: "Jodhpur's sinful fried pastry filled with khoya, dry fruits and nuts — soaked in sugar syrup. A Rajasthani pride.",
    ingredients: ["2 cups all-purpose flour","3 tbsp ghee","Water to knead","For filling: 1 cup khoya","¼ cup sugar","¼ cup mixed nuts (cashews, raisins, almonds)","½ tsp cardamom","Oil for frying","2 cups thin sugar syrup"],
    instructions: [
      "Make a medium-soft dough with flour, ghee, and water. Rest 20 minutes.",
      "Make filling: cook khoya with sugar and cardamom for 5 minutes. Add nuts. Cool.",
      "Roll small circles of dough. Fill generously with khoya mixture.",
      "Seal and shape into rounds. Press slightly flat.",
      "Deep fry on low-medium heat until golden all over — 10 minutes.",
      "Soak in sugar syrup for 3 minutes.",
      "Drain. Serve warm or at room temperature.",
    ],
    prepTime: 30, cookTime: 30, servings: 12,
    cuisineType: "Rajasthani", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Mawa Kachori Jodhpur"),
  },
  {
    title: "Paneer Kheer", category: "dessert",
    description: "Cottage cheese rice pudding — crumbled fresh paneer simmered in saffron and cardamom milk for a silky, protein-rich dessert.",
    ingredients: ["200g paneer, crumbled","1 litre full-fat milk","½ cup sugar","½ tsp cardamom powder","A generous pinch of saffron","2 tbsp basmati rice, soaked and ground","2 tbsp pistachios, slivered","1 tsp rose water"],
    instructions: [
      "Boil milk in a heavy pan. Add rice paste while stirring to prevent lumps.",
      "Add crumbled paneer. Stir well.",
      "Cook on medium heat, stirring frequently, for 25 minutes until thick.",
      "Add sugar, saffron, and cardamom. Cook 5 more minutes.",
      "Add rose water and most of the pistachios.",
      "Serve warm or chilled, garnished with remaining pistachios.",
    ],
    prepTime: 15, cookTime: 35, servings: 6,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Paneer Kheer"),
  },
  {
    title: "Vermicelli Kheer", category: "dessert",
    description: "Seviyan kheer — thin roasted vermicelli cooked in whole milk with saffron and cardamom. Made at Eid and throughout the year.",
    ingredients: ["1 cup thin vermicelli (seviyan)","1 litre full-fat milk","½ cup sugar","2 tbsp ghee","½ tsp cardamom powder","A generous pinch of saffron","¼ cup raisins","¼ cup cashews and almonds","1 tsp rose water"],
    instructions: [
      "Fry cashews and raisins in ghee until golden. Set aside.",
      "In the same ghee, fry vermicelli on medium heat until golden.",
      "Add milk and bring to a boil. Reduce heat and cook for 15 minutes, stirring often.",
      "Add sugar, saffron, and cardamom. Cook 5 more minutes.",
      "Add rose water and fried nuts.",
      "Serve warm or chilled.",
    ],
    prepTime: 5, cookTime: 25, servings: 6,
    cuisineType: "Pan-Indian", dietaryTags: [],
    imageUrl: null, youtubeUrl: yt("Seviyan Kheer Vermicelli"),
  },
  {
    title: "Mango Kheer", category: "dessert",
    description: "Chilled summer rice pudding with Alphonso mango pulp — fragrant with cardamom and saffron, naturally sweetened.",
    ingredients: ["¼ cup basmati rice","1 litre full-fat milk","½ cup sugar (adjust)","1 cup ripe mango pulp","½ tsp cardamom powder","A pinch of saffron","Mango pieces for garnish"],
    instructions: [
      "Cook rice in milk on medium-low heat, stirring often, for 35 minutes until thick.",
      "Add sugar, saffron, and cardamom. Stir for 10 more minutes.",
      "Cool completely.",
      "Fold in mango pulp gently.",
      "Refrigerate 2 hours.",
      "Serve chilled garnished with fresh mango pieces.",
    ],
    prepTime: 5, cookTime: 50, servings: 6,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mango Kheer Aam"),
  },
  {
    title: "Aam Papad", category: "dessert",
    description: "Sun-dried mango leather — raw mango pulp mixed with sugar and dried into tangy sweet sheets. Childhood nostalgia in every bite.",
    ingredients: ["2 cups raw mango pulp","1 cup sugar","½ tsp black salt","½ tsp cumin powder","¼ tsp chilli powder (optional)"],
    instructions: [
      "Cook mango pulp with sugar on low heat, stirring until sugar dissolves and mixture thickens slightly.",
      "Add black salt, cumin, and chilli if using. Mix.",
      "Grease a flat baking tray or plate.",
      "Pour a thin layer of mango mixture onto the tray.",
      "Sun dry for 2–3 days in direct sunlight, or dry in oven at 70°C for 3–4 hours.",
      "When completely dry and slightly leather-like, peel off the sheet.",
      "Cut into strips and roll up. Store in airtight container.",
    ],
    prepTime: 20, cookTime: 10, servings: 20,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Aam Papad Mango Leather"),
  },
  {
    title: "Poha Ladoo", category: "dessert",
    description: "Quick flattened rice ladoos with jaggery and coconut — a simple, wholesome sweet needing no cooking.",
    ingredients: ["2 cups thick poha (flattened rice)","¾ cup jaggery, grated","½ cup desiccated coconut","½ tsp cardamom powder","2 tbsp ghee","2 tbsp roasted peanuts, crushed"],
    instructions: [
      "Dry roast poha in a pan for 3 minutes until crisp. Cool.",
      "Grind poha to a coarse powder.",
      "Warm jaggery with 1 tbsp water until it just softens.",
      "Mix poha powder, coconut, jaggery, cardamom, ghee, and peanuts.",
      "Shape into balls while warm. If the mixture doesn't hold, add a few drops of warm ghee.",
      "Cool and store in airtight container.",
    ],
    prepTime: 15, cookTime: 5, servings: 15,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Poha Ladoo Flattened Rice"),
  },
  {
    title: "Kheer Kadam", category: "dessert",
    description: "Bengali novelty sweet — a rasgulla inside a khoya ball coated with tiny boondi. Sweet, spongy and layered in texture.",
    ingredients: ["10 small rasgullas (fresh or packaged)","1 cup khoya, crumbled","¼ cup powdered sugar","½ tsp cardamom","1 cup fine boondi (unsalted)","Pistachios"],
    instructions: [
      "Mix khoya with powdered sugar and cardamom. Knead to smooth.",
      "Squeeze out syrup from rasgullas gently.",
      "Flatten a ball of khoya in your palm. Place one rasgulla in centre.",
      "Wrap the khoya around the rasgulla to form a ball. Seal completely.",
      "Roll in fine boondi until coated all around.",
      "Press a pistachio on top.",
      "Refrigerate 1 hour before serving.",
    ],
    prepTime: 20, cookTime: 0, servings: 10,
    cuisineType: "Bengali", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kheer Kadam Bengali"),
  },
  {
    title: "Mango Mastani", category: "dessert",
    description: "Pune's legendary thick mango milkshake dessert — loaded with ice cream, dry fruits and topped with a cherry. A complete indulgence.",
    ingredients: ["2 cups ripe Alphonso mango pulp","2 cups chilled milk","4 scoops vanilla ice cream","2 tbsp sugar","¼ cup mixed dry fruits (cashews, raisins, almonds)","2 cherries for garnish","Saffron strands"],
    instructions: [
      "Blend mango pulp, milk, sugar, and 2 scoops of ice cream until thick and creamy.",
      "Pour into tall glasses.",
      "Top with remaining ice cream scoops.",
      "Scatter dry fruits and saffron strands over.",
      "Place a cherry on top.",
      "Serve immediately with a thick straw.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Maharashtrian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mango Mastani Pune"),
  },
  {
    title: "Basundi", category: "dessert",
    description: "Gujarat's version of rabri — milk reduced to a creamy thick consistency with saffron, cardamom and nutmeg. Utterly indulgent.",
    ingredients: ["2 litres full-fat milk","¾ cup sugar","½ tsp cardamom powder","A generous pinch of saffron","¼ tsp nutmeg, grated","2 tbsp pistachios and almonds, slivered"],
    instructions: [
      "Pour milk into a wide heavy pot. Bring to a boil.",
      "Simmer on medium-high heat, stirring every few minutes, for 50–60 minutes until milk reduces to half.",
      "Add sugar, saffron, cardamom, and nutmeg. Cook 10 more minutes.",
      "Cool and refrigerate. Basundi thickens further as it chills.",
      "Serve chilled, garnished with nuts.",
      "Optionally serve with puri.",
    ],
    prepTime: 5, cookTime: 70, servings: 8,
    cuisineType: "Gujarati", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Basundi Gujarati"),
  },
  {
    title: "Chikki", category: "dessert",
    description: "Mixed dry fruit and nut brittle in jaggery — festive, energy-boosting and satisfying. A healthier Indian candy.",
    ingredients: ["¼ cup cashews","¼ cup almonds","¼ cup pistachios","¼ cup raisins","1 cup jaggery","2 tbsp water","1 tsp ghee","½ tsp cardamom"],
    instructions: [
      "Lightly toast all nuts and keep warm.",
      "Melt jaggery with water to hard crack stage.",
      "Quickly stir in all nuts, raisins, and cardamom.",
      "Pour onto a greased plate. Spread evenly with greased spatula.",
      "Score immediately into pieces.",
      "Cool completely before breaking.",
    ],
    prepTime: 10, cookTime: 15, servings: 20,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mixed Nut Chikki"),
  },
  {
    title: "Panjiri", category: "dessert",
    description: "Punjabi winter dry sweet powder eaten to warm the body — roasted wheat flour with edible gum, sugar, nuts and desi ghee.",
    ingredients: ["2 cups whole wheat flour","½ cup ghee","½ cup powdered sugar","2 tbsp edible gum (gond), fried","¼ cup almonds, chopped","¼ cup cashews, chopped","2 tbsp dry ginger powder","1 tsp cardamom powder","1 tbsp poppy seeds"],
    instructions: [
      "Fry edible gum in ghee until it puffs up. Remove and crush.",
      "In the same ghee, roast wheat flour on low heat for 20 minutes until golden.",
      "Cool the roasted flour.",
      "Mix in powdered sugar, crushed gond, nuts, dry ginger, cardamom, and poppy seeds.",
      "Store in an airtight jar. Serve 2 tablespoons daily in winter.",
      "Can be eaten dry or mixed with warm milk.",
    ],
    prepTime: 10, cookTime: 25, servings: 20,
    cuisineType: "Punjabi", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Panjiri Punjabi winter sweet"),
  },
  {
    title: "Therattipal", category: "dessert",
    description: "Tamil Nadu's reduced milk sweet — milk cooked down until it becomes a thick, crumbly, caramelised sweet with ghee.",
    ingredients: ["2 litres full-fat milk","¾ cup sugar","3 tbsp ghee","½ tsp cardamom powder"],
    instructions: [
      "Boil milk in a wide heavy pan.",
      "Cook on medium heat, stirring every 2–3 minutes, scraping the sides.",
      "As milk reduces and thickens (after about 40 minutes), stir more frequently.",
      "Add sugar and ghee. Continue cooking and stirring.",
      "The milk will eventually become very thick and start to leave the sides — 60–70 minutes total.",
      "Add cardamom. Remove when it resembles thick ricotta.",
      "Cool, shape into rounds, or serve as is.",
    ],
    prepTime: 5, cookTime: 75, servings: 6,
    cuisineType: "South Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Therattipal Tamil sweet"),
  },
  {
    title: "Doodh Peda", category: "dessert",
    description: "Milk fudge made from scratch using condensed milk and milk powder — soft, quick and studded with pistachios.",
    ingredients: ["1 cup condensed milk","½ cup milk powder","1 tbsp ghee","½ tsp cardamom powder","Pistachios for pressing on top"],
    instructions: [
      "Mix condensed milk, milk powder, and ghee in a heavy pan.",
      "Cook on low heat, stirring continuously, until the mixture thickens and leaves the sides — 10–12 minutes.",
      "Remove from heat. Add cardamom.",
      "Cool until handleable. Shape into small round discs.",
      "Press a pistachio sliver into the centre of each peda.",
      "Refrigerate 30 minutes before serving.",
    ],
    prepTime: 5, cookTime: 15, servings: 15,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Doodh Peda Milk Fudge"),
  },
];
