function yt(title: string) {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(title + " indian recipe homemade")}`;
}

export const mocktailSeedData = [
  // ── LASSI VARIETIES ──────────────────────────────────────────────────────────
  {
    title: "Mango Lassi", category: "mocktail",
    description: "Punjab's ultimate summer drink — thick, creamy yogurt blended with Alphonso mango pulp, cardamom and a pinch of saffron.",
    ingredients: ["1 cup ripe mango pulp (Alphonso)","1 cup full-fat yogurt","½ cup chilled milk","3 tbsp sugar","½ tsp cardamom powder","A pinch of saffron in 1 tbsp warm milk","Ice cubes"],
    instructions: [
      "Blend mango pulp, yogurt, milk, and sugar until smooth and frothy.",
      "Add cardamom and saffron milk. Blend again briefly.",
      "Taste and adjust sweetness.",
      "Pour into tall chilled glasses over ice.",
      "Garnish with a pinch of cardamom and a mango sliver.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Punjabi", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mango Lassi"),
  },
  {
    title: "Sweet Lassi", category: "mocktail",
    description: "Classic chilled yogurt drink — simple, thick and creamy, sweetened with sugar and rose water. Punjab's everyday cooling drink.",
    ingredients: ["2 cups full-fat yogurt","½ cup chilled water or milk","3 tbsp sugar","½ tsp cardamom powder","1 tsp rose water","Ice cubes","A pinch of saffron and pistachios for garnish"],
    instructions: [
      "Blend yogurt, water, sugar, and cardamom until frothy.",
      "Add rose water. Blend 10 seconds more.",
      "Pour over ice in tall glasses.",
      "Garnish with saffron strands and slivered pistachios.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Punjabi", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Sweet Lassi"),
  },
  {
    title: "Salty Lassi", category: "mocktail",
    description: "Savoury cumin-spiced buttermilk drink — the ideal accompaniment to heavy Punjabi meals, cooling and digestive.",
    ingredients: ["2 cups yogurt","1 cup chilled water","½ tsp cumin powder, roasted","¼ tsp black salt","Salt to taste","A few mint leaves","Ice cubes"],
    instructions: [
      "Blend yogurt and water until smooth.",
      "Add cumin powder, black salt, and regular salt.",
      "Blend briefly.",
      "Tear mint leaves and add. Blend 5 seconds.",
      "Pour over ice. Garnish with a sprig of mint and a pinch of roasted cumin.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Punjabi", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Salty Lassi Chach"),
  },
  {
    title: "Rose Lassi", category: "mocktail",
    description: "Fragrant pink lassi with rose syrup, saffron and cream — a festive version of the classic, layered and eye-catching.",
    ingredients: ["1½ cups thick yogurt","½ cup chilled milk","3 tbsp rose syrup","1 tsp saffron water","2 tbsp fresh cream","Ice cubes","Dried rose petals and pistachios for garnish"],
    instructions: [
      "Blend yogurt, milk, and 2 tbsp rose syrup until smooth.",
      "Add saffron water. Mix.",
      "Pour into glasses over ice.",
      "Drizzle remaining rose syrup and cream on top.",
      "Garnish with dried rose petals and slivered pistachios.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Punjabi", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Rose Lassi recipe"),
  },
  {
    title: "Strawberry Lassi", category: "mocktail",
    description: "Fresh strawberry and yogurt blended into a vibrant pink lassi — naturally sweet, slightly tart and utterly refreshing.",
    ingredients: ["1 cup fresh strawberries","1½ cups yogurt","½ cup milk","2 tbsp sugar (adjust)","½ tsp cardamom","Ice cubes","Strawberry slices for garnish"],
    instructions: [
      "Blend strawberries until smooth.",
      "Add yogurt, milk, sugar, and cardamom. Blend until frothy.",
      "Taste and adjust sweetness.",
      "Pour over ice.",
      "Garnish with strawberry slices.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Strawberry Lassi"),
  },
  // ── TRADITIONAL INDIAN DRINKS ─────────────────────────────────────────────────
  {
    title: "Aam Panna", category: "mocktail",
    description: "Raw green mango summer cooler — tangy, sweet and spiced with cumin and black salt. India's favourite heat-stroke remedy.",
    ingredients: ["2 raw green mangoes","¾ cup sugar","1 tsp roasted cumin powder","1 tsp black salt","Regular salt to taste","A few mint leaves","Cold water to dilute","Ice cubes"],
    instructions: [
      "Boil or roast raw mangoes until soft. Cool, peel and extract the pulp.",
      "Blend pulp with sugar, cumin powder, black salt, and mint until smooth.",
      "Strain through a sieve for a smooth concentrate.",
      "Refrigerate the concentrate.",
      "To serve: mix 3 tbsp concentrate with 1 cup cold water. Stir.",
      "Serve over ice with a pinch of extra cumin on top.",
    ],
    prepTime: 15, cookTime: 20, servings: 6,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Aam Panna Raw Mango"),
  },
  {
    title: "Jal Jeera", category: "mocktail",
    description: "Cumin-spiced tangy tamarind water — India's most refreshing street drink. Thirst-quenching, digestive and utterly distinctive.",
    ingredients: ["1 tsp cumin seeds, roasted and ground","½ cup tamarind water (soaked tamarind)","2 tbsp fresh mint leaves","2 tbsp fresh coriander","1 tsp black salt","1 tbsp sugar","½ tsp amchur (dry mango powder)","3 cups cold water","Ice cubes"],
    instructions: [
      "Blend tamarind water with mint, coriander, cumin powder, black salt, sugar, and amchur.",
      "Strain through fine mesh.",
      "Mix with cold water. Taste and adjust seasoning — should be tangy, spiced and refreshing.",
      "Refrigerate.",
      "Serve over ice, garnished with a mint sprig.",
      "Can be prepared as a concentrate and diluted to taste.",
    ],
    prepTime: 15, cookTime: 0, servings: 4,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Jal Jeera recipe"),
  },
  {
    title: "Thandai", category: "mocktail",
    description: "Holi and Shivratri's festive chilled milk drink — blended with almonds, fennel, rose petals, cardamom and cooling spices.",
    ingredients: ["1 litre chilled full-fat milk","¼ cup almonds, soaked and peeled","2 tbsp fennel seeds, soaked","1 tbsp poppy seeds, soaked","10 black peppercorns","½ tsp cardamom powder","1 tsp rose water","3 tbsp sugar","A pinch of saffron","Dried rose petals for garnish"],
    instructions: [
      "Soak almonds, fennel seeds, and poppy seeds in water for 2 hours.",
      "Grind soaked almonds, fennel, poppy seeds, and peppercorns to a smooth paste with little milk.",
      "Mix paste with remaining milk. Add sugar, cardamom, saffron, and rose water.",
      "Strain through a muslin cloth, pressing to extract all liquid.",
      "Refrigerate at least 2 hours.",
      "Serve chilled in glasses, garnished with rose petals and a pinch of saffron.",
    ],
    prepTime: 130, cookTime: 0, servings: 4,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Thandai recipe"),
  },
  {
    title: "Chaas", category: "mocktail",
    description: "Digestive spiced buttermilk — thin, tangy and seasoned with curry leaves, green chilli and ginger. Gujarat's meal companion.",
    ingredients: ["1 cup yogurt","2 cups chilled water","½ tsp roasted cumin powder","¼ tsp black salt","A few curry leaves","1 green chilli, slit","½ tsp grated ginger","Salt to taste","Fresh coriander"],
    instructions: [
      "Blend yogurt and water until completely smooth.",
      "Add cumin powder, black salt, ginger, and regular salt. Mix.",
      "Temper in 1 tsp oil: add curry leaves and green chilli until they splutter.",
      "Pour tempering into the chaas. Stir.",
      "Garnish with fresh coriander.",
      "Serve at room temperature or chilled.",
    ],
    prepTime: 5, cookTime: 3, servings: 3,
    cuisineType: "Gujarati", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Chaas Masala Buttermilk"),
  },
  {
    title: "Nimbu Pani", category: "mocktail",
    description: "The Indian lemonade — freshly squeezed lemon with sugar, black salt, cumin and mint. Simple, refreshing and universally loved.",
    ingredients: ["4 lemons, juiced","3 tbsp sugar","½ tsp black salt","A pinch of roasted cumin powder","Mint leaves","4 cups cold water","Ice cubes"],
    instructions: [
      "Squeeze lemons. Strain the juice.",
      "Mix sugar in 2 tbsp warm water to dissolve. Make a simple syrup.",
      "Combine lemon juice, sugar syrup, cold water, black salt, and cumin.",
      "Stir well. Taste and adjust lemon or sugar.",
      "Add mint leaves and ice.",
      "Serve immediately.",
    ],
    prepTime: 5, cookTime: 0, servings: 4,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Nimbu Pani Lemonade"),
  },
  {
    title: "Kokum Sharbat", category: "mocktail",
    description: "Goa and Maharashtra's prized purple drink — kokum extract with sugar, cumin and mint. Deep ruby coloured and delightfully tart.",
    ingredients: ["10 kokum pieces","3 cups water","4 tbsp sugar","½ tsp roasted cumin powder","A pinch of black salt","Fresh mint leaves","Ice cubes"],
    instructions: [
      "Soak kokum in 1 cup warm water for 30 minutes until it rehydrates and releases its colour.",
      "Squeeze and strain the kokum liquid.",
      "Dissolve sugar in the kokum extract.",
      "Add cumin powder and black salt. Mix.",
      "Dilute with remaining 2 cups cold water.",
      "Serve over ice with fresh mint.",
    ],
    prepTime: 35, cookTime: 0, servings: 4,
    cuisineType: "Maharashtrian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kokum Sharbat recipe"),
  },
  {
    title: "Rose Sharbat", category: "mocktail",
    description: "Chilled rose petal syrup diluted with chilled milk or water — fragrant, pink and elegant. Essential at Indian celebrations.",
    ingredients: ["4 tbsp rose syrup (rooh afza)","2 cups chilled milk OR cold water","Ice cubes","Sabja (basil) seeds, soaked","Rose petals and pistachios for garnish"],
    instructions: [
      "Soak sabja seeds in water for 20 minutes until they bloom.",
      "Pour rose syrup into glasses.",
      "Add ice cubes.",
      "Pour chilled milk over gently.",
      "Add bloomed sabja seeds.",
      "Garnish with rose petals and pistachios.",
    ],
    prepTime: 25, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Rose Sharbat Rooh Afza"),
  },
  {
    title: "Bel Sharbat", category: "mocktail",
    description: "Wood apple (bael fruit) summer drink — this tart, earthy fruit blended with sugar and spices is India's ancient cooling drink.",
    ingredients: ["1 ripe bael fruit","4 tbsp sugar","½ tsp cardamom powder","A pinch of black salt","1 tsp roasted cumin powder","3 cups cold water","Ice cubes","Mint for garnish"],
    instructions: [
      "Break open the bael fruit. Scoop out the pulp.",
      "Mix pulp with 1 cup warm water and mash well.",
      "Strain through a sieve, pressing to extract all juice.",
      "Dissolve sugar in the strained juice.",
      "Add cardamom, black salt, and cumin.",
      "Dilute with remaining cold water.",
      "Serve over ice with mint.",
    ],
    prepTime: 15, cookTime: 0, servings: 4,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Bael Sharbat Wood Apple"),
  },
  {
    title: "Sattu Sharbat", category: "mocktail",
    description: "Bihar's super-food energy drink — roasted chickpea flour (sattu) mixed with lemon, black salt and cumin. Protein-packed and cooling.",
    ingredients: ["4 tbsp sattu (roasted chickpea flour)","1 lemon, juiced","1 tsp black salt","½ tsp cumin powder","1 tbsp jaggery or sugar","3 cups cold water","Mint and ginger for garnish"],
    instructions: [
      "Dissolve sattu in ½ cup cold water, stirring vigorously to avoid lumps.",
      "Add lemon juice, black salt, cumin, and jaggery.",
      "Add remaining cold water. Mix well.",
      "Taste and adjust seasoning — should be tangy and salty.",
      "Serve immediately with ice, mint, and grated ginger.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "East Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Sattu Sharbat Bihar"),
  },
  {
    title: "Khas Sharbat", category: "mocktail",
    description: "Vetiver (khus) root green sharbat — intensely fragrant and earth-cooling. North India's Ramadan and summer speciality.",
    ingredients: ["4 tbsp khas (vetiver) syrup","2 cups chilled water OR milk","Ice cubes","Lemon slices","Mint leaves","Sabja seeds, soaked (optional)"],
    instructions: [
      "Soak sabja seeds in water for 20 minutes if using.",
      "Add khas syrup to glasses.",
      "Fill with chilled water or milk.",
      "Add ice cubes.",
      "Add sabja seeds.",
      "Garnish with lemon slice and mint.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Khas Vetiver Sharbat"),
  },
  // ── FRESH JUICES ──────────────────────────────────────────────────────────────
  {
    title: "Fresh Pomegranate Juice", category: "mocktail",
    description: "Freshly extracted ruby pomegranate juice with a hint of black salt and lemon — packed with antioxidants and stunning to look at.",
    ingredients: ["4 large pomegranates","1 tsp black salt","1 lemon, juiced","1 tsp sugar (optional)","Ice cubes","Mint for garnish"],
    instructions: [
      "Deseed pomegranates. Place seeds in a blender.",
      "Blend on low speed for 30 seconds — just enough to extract juice without crushing the bitter membranes.",
      "Strain through fine mesh immediately.",
      "Add black salt, lemon juice, and sugar.",
      "Pour over ice. Garnish with a few seeds and mint.",
      "Serve immediately as pomegranate juice oxidises quickly.",
    ],
    prepTime: 15, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Fresh Pomegranate Juice"),
  },
  {
    title: "Sugarcane Juice", category: "mocktail",
    description: "India's iconic street juice — freshly pressed sugarcane with ginger and lemon, a natural instant energy booster.",
    ingredients: ["500g sugarcane pieces (or use a juicer)","1-inch ginger piece","1 lemon, juiced","A pinch of black salt","Ice cubes","Mint leaves"],
    instructions: [
      "Pass sugarcane through a sugarcane press or juicer to extract fresh juice.",
      "Grate ginger and squeeze ginger juice into the cane juice.",
      "Add lemon juice and black salt.",
      "Strain through fine mesh.",
      "Serve immediately over ice with mint.",
      "Fresh sugarcane juice must be consumed within 15 minutes.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Sugarcane Juice Ganna"),
  },
  {
    title: "Carrot Ginger Juice", category: "mocktail",
    description: "Vibrant orange juice with a fiery ginger kick — nutrient-dense, immune-boosting and beautiful in the glass.",
    ingredients: ["6 medium carrots, peeled","1-inch fresh ginger","1 lemon, juiced","1 tsp honey or sugar","A pinch of black pepper","Ice cubes"],
    instructions: [
      "Pass carrots and ginger through a juicer.",
      "Add lemon juice and honey. Mix.",
      "Add a tiny pinch of black pepper — it enhances the ginger flavour.",
      "Strain if desired.",
      "Serve immediately over ice.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Carrot Ginger Juice"),
  },
  {
    title: "Beetroot Apple Juice", category: "mocktail",
    description: "Deep ruby red detox juice — earthy beetroot and sweet apple balanced with lemon and ginger. Stunning colour, remarkable nutrition.",
    ingredients: ["2 medium beetroots, peeled","2 apples, cored","1-inch ginger","1 lemon, juiced","1 tsp honey","A pinch of black salt","Ice cubes"],
    instructions: [
      "Pass beetroot, apples, and ginger through a juicer.",
      "Add lemon juice, honey, and black salt. Mix.",
      "Taste and adjust. Apple sweetness varies.",
      "Serve immediately over ice.",
      "This juice is best drunk within 30 minutes for maximum nutrition.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Beetroot Apple Juice"),
  },
  {
    title: "Watermelon Mint Juice", category: "mocktail",
    description: "Summer in a glass — pure watermelon juice with fresh mint, black salt and a squeeze of lemon. Simple perfection.",
    ingredients: ["½ medium watermelon, cubed, seeds removed","10 fresh mint leaves","1 lemon, juiced","A pinch of black salt","A pinch of cumin powder","Ice cubes"],
    instructions: [
      "Blend watermelon until smooth. Strain if desired.",
      "Add mint leaves and blend briefly.",
      "Mix in lemon juice, black salt, and cumin.",
      "Pour over ice.",
      "Garnish with a mint sprig and a wedge of watermelon.",
    ],
    prepTime: 10, cookTime: 0, servings: 3,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Watermelon Mint Juice"),
  },
  {
    title: "Pineapple Mint Cooler", category: "mocktail",
    description: "Tropical Indian cooler — fresh pineapple juice with mint, ginger and a hint of black salt. Brilliantly tart and refreshing.",
    ingredients: ["½ pineapple, peeled and cubed","10 fresh mint leaves","1-inch ginger","1 lime, juiced","1 tbsp sugar","A pinch of black salt","Soda water (optional)","Ice cubes"],
    instructions: [
      "Juice pineapple chunks through a juicer or blend and strain.",
      "Muddle mint leaves with ginger in a glass.",
      "Add pineapple juice, lime juice, sugar, and black salt.",
      "Stir or shake well.",
      "Pour over ice. Top with soda water if desired.",
      "Garnish with pineapple chunks and mint.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Pineapple Mint Cooler"),
  },
  {
    title: "Mosambi Juice", category: "mocktail",
    description: "Sweet lime juice — freshly squeezed mosambi (sweet lime) is India's most beloved fresh fruit juice, served at every juice stall.",
    ingredients: ["8 mosambi (sweet lime) fruits","1 tsp black salt","½ tsp cumin powder","Ice cubes","Mint leaves"],
    instructions: [
      "Squeeze mosambi through a citrus juicer or press.",
      "Strain to remove seeds and pulp if desired.",
      "Add black salt and cumin powder.",
      "Stir well.",
      "Serve immediately over ice with mint.",
      "Do NOT store — mosambi juice turns bitter within 15 minutes.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mosambi Sweet Lime Juice"),
  },
  {
    title: "Guava Cooler", category: "mocktail",
    description: "Pink guava juice with chilli, black salt and lemon — India's favourite seasonal fruit becomes a perfectly spiced drink.",
    ingredients: ["4 ripe pink guavas","2 tbsp sugar","1 lemon, juiced","½ tsp black salt","A pinch of red chilli powder","2 cups cold water","Ice cubes","Mint"],
    instructions: [
      "Quarter guavas and blend with 1 cup water until smooth.",
      "Strain through a fine sieve, pressing to extract all juice.",
      "Add remaining water, sugar, lemon, black salt, and chilli powder.",
      "Mix well. Taste and adjust.",
      "Serve over ice with mint.",
    ],
    prepTime: 10, cookTime: 0, servings: 3,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Guava Juice Amrud"),
  },
  {
    title: "Litchi Mint Mocktail", category: "mocktail",
    description: "Fresh litchi juice with mint and lemon — delicately sweet, floral and impossibly refreshing for Indian summers.",
    ingredients: ["20 fresh litchis, peeled and deseeded","10 mint leaves","1 lime, juiced","1 tbsp sugar","Soda water","Ice cubes","Lime rounds for garnish"],
    instructions: [
      "Blend litchis until smooth. Strain through a sieve.",
      "Muddle mint leaves with lime juice and sugar in a glass.",
      "Add litchi juice. Stir well.",
      "Fill glass with ice.",
      "Top with soda water.",
      "Garnish with lime rounds and mint sprigs.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Litchi Mocktail"),
  },
  {
    title: "Virgin Mojito Indian Style", category: "mocktail",
    description: "Indian-style mint mojito with green mango, lemon and ginger — a tangy-minty sparkling drink that's both cooling and exciting.",
    ingredients: ["10 fresh mint leaves","1 green chilli, deseeded (optional)","2 lime wedges","1 tsp sugar","2 tbsp raw mango pulp or aam panna","A pinch of black salt","100ml soda water","Ice cubes"],
    instructions: [
      "Muddle mint leaves, lime wedges, chilli, and sugar in a glass until fragrant.",
      "Add raw mango pulp and black salt. Stir.",
      "Fill glass with crushed ice.",
      "Pour soda water over slowly.",
      "Stir gently with a long spoon.",
      "Garnish with a mint sprig and lime wedge.",
    ],
    prepTime: 5, cookTime: 0, servings: 1,
    cuisineType: "Fusion", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Indian Virgin Mojito Green Mango"),
  },
  // ── MILKSHAKES ────────────────────────────────────────────────────────────────
  {
    title: "Banana Milkshake", category: "mocktail",
    description: "Thick, creamy banana milkshake with cardamom — nourishing, naturally sweet and beloved by kids across India.",
    ingredients: ["3 ripe bananas","2 cups cold full-fat milk","2 tbsp sugar (adjust)","½ tsp cardamom powder","2 scoops vanilla ice cream","Ice cubes"],
    instructions: [
      "Peel and freeze bananas for 30 minutes for an extra thick shake.",
      "Blend bananas, milk, sugar, and cardamom until smooth.",
      "Add ice cream and blend again briefly.",
      "Pour into tall chilled glasses.",
      "Garnish with banana slice and a pinch of cardamom.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Banana Milkshake"),
  },
  {
    title: "Chikoo Milkshake", category: "mocktail",
    description: "Sapodilla (chikoo) milkshake — silky smooth, naturally caramel-sweet and deeply indulgent. A true Maharashtra childhood classic.",
    ingredients: ["4 ripe chikoos (sapodilla), peeled and deseeded","2 cups cold full-fat milk","2 tbsp sugar","½ tsp cardamom","2 scoops vanilla ice cream","Ice cubes"],
    instructions: [
      "Remove seeds from chikoos. Blend with cold milk until completely smooth.",
      "Add sugar, cardamom, and ice cream. Blend until frothy.",
      "Pour into tall glasses over ice.",
      "The natural sweetness of chikoo means you may need less sugar.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Chikoo Milkshake Sapodilla"),
  },
  {
    title: "Badam Milk", category: "mocktail",
    description: "Saffron-golden almond milk — soaked almonds ground with saffron-infused warm milk, chilled and served. A royal Indian drink.",
    ingredients: ["20 almonds, soaked overnight and peeled","1 litre full-fat milk","3 tbsp sugar","½ tsp cardamom powder","A generous pinch of saffron in 2 tbsp warm milk","Slivered pistachios for garnish"],
    instructions: [
      "Grind soaked, peeled almonds to a fine paste with 2 tbsp milk.",
      "Boil remaining milk. Add almond paste and stir well.",
      "Add sugar, saffron milk, and cardamom.",
      "Cook on medium heat for 10 minutes until slightly thickened.",
      "Cool completely. Refrigerate.",
      "Serve chilled with slivered pistachios — or serve warm on cold nights.",
    ],
    prepTime: 480, cookTime: 15, servings: 4,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Badam Milk Almond Milk Indian"),
  },
  {
    title: "Haldi Doodh", category: "mocktail",
    description: "Golden milk — warm turmeric milk with ginger, cardamom and black pepper. India's ancient immunity booster and bedtime ritual.",
    ingredients: ["2 cups full-fat milk","1 tsp turmeric powder","½ tsp ginger, grated or powdered","A pinch of black pepper","¼ tsp cardamom powder","1 tbsp honey or jaggery","1 tsp ghee (optional)"],
    instructions: [
      "Warm milk in a small saucepan on medium heat.",
      "Add turmeric, ginger, cardamom, and black pepper.",
      "Whisk gently as it heats — do not boil.",
      "Remove from heat. Add honey or jaggery.",
      "Add a tiny drop of ghee if desired — it enhances absorption of turmeric.",
      "Pour into mugs and serve warm.",
    ],
    prepTime: 5, cookTime: 8, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Haldi Doodh Golden Milk"),
  },
  {
    title: "Dry Fruit Milkshake", category: "mocktail",
    description: "Rich and nourishing dry fruit milkshake — almonds, cashews, dates and saffron blended with whole milk. A festive Indian treat.",
    ingredients: ["10 almonds, soaked","8 cashews","4 medjool dates, pitted","2 tbsp raisins","2 cups cold full-fat milk","½ tsp cardamom","A pinch of saffron","1 tsp sugar (optional)","Ice cubes"],
    instructions: [
      "Soak almonds for 4 hours. Peel.",
      "Blend almonds, cashews, dates, and raisins with ½ cup milk until smooth.",
      "Add remaining milk, cardamom, and saffron. Blend until frothy.",
      "Taste and add sugar only if needed — dates provide natural sweetness.",
      "Serve over ice or warm as a nourishing drink.",
    ],
    prepTime: 245, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Dry Fruit Milkshake"),
  },
  {
    title: "Cold Coffee", category: "mocktail",
    description: "Indian-style cold coffee — thick, frothy and sweet, blended with ice cream and cold milk. The café classic made at home.",
    ingredients: ["2 tsp instant coffee","2 tbsp sugar","2 tbsp hot water","2 cups cold full-fat milk","2 scoops vanilla ice cream","Ice cubes","Chocolate syrup for garnish"],
    instructions: [
      "Dissolve instant coffee in hot water. Cool completely.",
      "Blend coffee, sugar, milk, and ice cream until very frothy.",
      "Pour over ice in tall glasses.",
      "Drizzle chocolate syrup on top.",
      "For extra thick: add more ice cream and less milk.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Cold Coffee Indian style"),
  },
  // ── MODERN INDIAN MOCKTAILS ────────────────────────────────────────────────────
  {
    title: "Shikanji", category: "mocktail",
    description: "Delhi's street lemonade — freshly squeezed lemon with black salt, roasted cumin and optional dried ginger. Quick, cheap and perfect.",
    ingredients: ["4 lemons, juiced","4 tbsp sugar","½ tsp black salt","½ tsp cumin powder, roasted","¼ tsp dry ginger powder","4 cups cold water","Ice cubes","Lemon slices for garnish"],
    instructions: [
      "Make sugar syrup by dissolving sugar in 2 tbsp hot water. Cool.",
      "Mix lemon juice with cold water.",
      "Add sugar syrup, black salt, cumin powder, and dry ginger.",
      "Mix well. Taste and adjust seasoning.",
      "Pour over ice.",
      "Garnish with lemon slices.",
    ],
    prepTime: 5, cookTime: 0, servings: 4,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Shikanji Delhi Lemonade"),
  },
  {
    title: "Kiwi Mint Mocktail", category: "mocktail",
    description: "Vibrant green kiwi and mint cooler — tangy, sweet and utterly refreshing with a fizzy finish.",
    ingredients: ["4 ripe kiwis, peeled","10 mint leaves","1 lime, juiced","2 tbsp sugar","Soda water","Ice cubes","Kiwi slices for garnish"],
    instructions: [
      "Blend kiwis until smooth. Strain if desired.",
      "Muddle mint leaves with sugar and lime juice in a jug.",
      "Add kiwi juice. Stir well.",
      "Pour into glasses over ice.",
      "Top with soda water.",
      "Garnish with kiwi slices and mint.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Fusion", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kiwi Mint Mocktail"),
  },
  {
    title: "Strawberry Lemonade", category: "mocktail",
    description: "Summer's most loved cooler — freshly muddled strawberries with lemon, sugar and chilled water. Naturally vibrant pink.",
    ingredients: ["1 cup fresh strawberries","4 lemons, juiced","4 tbsp sugar","4 cups cold water","Ice cubes","Strawberry slices and mint for garnish"],
    instructions: [
      "Blend strawberries until smooth. Strain.",
      "Make sugar syrup with sugar and 2 tbsp hot water.",
      "Mix strawberry juice, lemon juice, sugar syrup, and cold water.",
      "Taste and adjust — more lemon for tartness, more sugar for sweetness.",
      "Pour over ice.",
      "Garnish with strawberry slices and mint.",
    ],
    prepTime: 10, cookTime: 0, servings: 4,
    cuisineType: "Fusion", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Strawberry Lemonade"),
  },
  {
    title: "Mixed Fruit Punch", category: "mocktail",
    description: "Festive fruit punch — mango, orange, pineapple and lemon juices with a dash of rose water and ginger. Party in a glass.",
    ingredients: ["1 cup mango juice","1 cup orange juice","1 cup pineapple juice","2 lemons, juiced","1 tsp rose water","½-inch ginger, grated","2 tbsp sugar","Soda water","Ice cubes","Mixed fruit and mint for garnish"],
    instructions: [
      "Mix all fruit juices together.",
      "Add lemon juice, rose water, ginger juice, and sugar.",
      "Taste and adjust sweetness.",
      "Refrigerate for 1 hour.",
      "Serve over ice, topped with soda water.",
      "Garnish with fresh fruit and mint.",
    ],
    prepTime: 15, cookTime: 0, servings: 6,
    cuisineType: "Fusion", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mixed Fruit Punch Indian"),
  },
  {
    title: "Tamarind Soda", category: "mocktail",
    description: "Imli soda — sweet-sour tamarind concentrate with spices topped with soda water. Street food in a glass.",
    ingredients: ["4 tbsp tamarind paste","4 tbsp sugar","1 tsp black salt","½ tsp cumin powder","A pinch of red chilli powder","Cold soda water","Ice cubes","Mint for garnish"],
    instructions: [
      "Mix tamarind paste with sugar, black salt, cumin, and chilli powder.",
      "Add 2 tbsp warm water to dissolve. Mix to smooth concentrate.",
      "Taste — it should be tangy, sweet and spiced.",
      "Place 2 tbsp concentrate in each glass.",
      "Add ice cubes.",
      "Top with cold soda water. Garnish with mint.",
    ],
    prepTime: 5, cookTime: 0, servings: 4,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Tamarind Soda Imli Drink"),
  },
  {
    title: "Coconut Lemonade", category: "mocktail",
    description: "Refreshing coconut water with fresh lemon juice, mint and a pinch of pink Himalayan salt. Naturally electrolyte-rich.",
    ingredients: ["2 cups fresh coconut water","2 lemons, juiced","2 tbsp honey or sugar","10 mint leaves","A pinch of Himalayan pink salt","Ice cubes","Coconut pieces for garnish"],
    instructions: [
      "Combine fresh coconut water and lemon juice.",
      "Add honey and salt. Stir until dissolved.",
      "Muddle mint leaves and add.",
      "Pour over ice.",
      "Garnish with coconut pieces and mint.",
      "Best served immediately as coconut water loses freshness quickly.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Coconut Lemonade"),
  },
  {
    title: "Ginger Lemon Fizz", category: "mocktail",
    description: "Fiery Indian ginger beer-style drink — fresh ginger syrup with lemon and soda. Warming and cooling at the same time.",
    ingredients: ["2-inch fresh ginger, juiced or grated","2 lemons, juiced","3 tbsp sugar","A pinch of black salt","Cold soda water","Ice cubes","Lemon slices and candied ginger for garnish"],
    instructions: [
      "Make ginger syrup: simmer sugar with ½ cup water and ginger slices for 5 minutes. Cool and strain.",
      "Mix ginger syrup with lemon juice and black salt.",
      "Pour into glasses over ice.",
      "Top generously with soda water.",
      "Garnish with lemon slices and candied ginger.",
    ],
    prepTime: 5, cookTime: 5, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Ginger Lemon Fizz Mocktail"),
  },
  {
    title: "Cucumber Cooler", category: "mocktail",
    description: "Clean, refreshing cucumber and mint juice with lemon and black salt — the lightest, most cooling summer drink.",
    ingredients: ["2 cucumbers, peeled and roughly chopped","10 mint leaves","1 lemon, juiced","1 green chilli (optional)","1 tsp sugar","½ tsp black salt","Cold water","Ice cubes"],
    instructions: [
      "Blend cucumber with mint, lemon juice, chilli, sugar, and black salt.",
      "Add a little cold water to help blend.",
      "Strain through fine mesh.",
      "Adjust water to desired consistency.",
      "Serve over ice.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Cucumber Cooler Drink"),
  },
  {
    title: "Rooh Afza Milk", category: "mocktail",
    description: "The timeless Indian summer drink — chilled rose-scented syrup stirred into full-fat milk with sabja seeds. Nostalgia in every sip.",
    ingredients: ["4 tbsp Rooh Afza syrup","2 cups chilled full-fat milk","2 tbsp sabja (basil) seeds, soaked","Ice cubes","Rose petals for garnish"],
    instructions: [
      "Soak sabja seeds in water for 20 minutes until fully bloomed.",
      "Pour Rooh Afza into tall glasses.",
      "Add ice cubes.",
      "Pour chilled milk over gently — the beautiful pink and white layers will form.",
      "Add bloomed sabja seeds.",
      "Garnish with rose petals. Stir before drinking.",
    ],
    prepTime: 25, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Rooh Afza Milk Drink"),
  },
  {
    title: "Spinach Apple Detox Juice", category: "mocktail",
    description: "Vibrant green health juice — baby spinach, green apple, cucumber and lemon blended together. An Indian wellness staple.",
    ingredients: ["2 cups baby spinach","2 green apples, cored","1 cucumber","1 lemon, juiced","1-inch ginger","1 tsp honey","Ice cubes"],
    instructions: [
      "Pass spinach, apple, cucumber, and ginger through a juicer.",
      "Add lemon juice and honey. Mix.",
      "Serve immediately over ice — green juices lose nutrition quickly.",
      "Can also be blended (with water) and strained for a smoother version.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Fusion", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Spinach Apple Detox Juice"),
  },
  {
    title: "Kokum Juice", category: "mocktail",
    description: "Goan-style fresh kokum juice — just kokum, water, sugar and salt. Cooling, blood pressure-balancing and deeply tart.",
    ingredients: ["15 kokum pieces","3 cups warm water","3 tbsp sugar","½ tsp black salt","½ tsp cumin powder","Ice cubes","Fresh coriander"],
    instructions: [
      "Soak kokum in warm water for 45 minutes until it softens completely and releases its juice.",
      "Squeeze and strain the deep purple juice thoroughly.",
      "Dissolve sugar in the juice. Add black salt and cumin.",
      "Taste — should be deeply tart, slightly sweet, and pleasantly salty.",
      "Dilute with a little cold water if too concentrated.",
      "Serve over ice with fresh coriander.",
    ],
    prepTime: 50, cookTime: 0, servings: 3,
    cuisineType: "Maharashtrian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kokum Juice Sol Kadhi"),
  },
  {
    title: "Masala Chaas", category: "mocktail",
    description: "Full-flavoured spiced buttermilk with tempered mustard seeds, ginger, and curry leaves — a full-bodied digestive drink.",
    ingredients: ["1½ cups yogurt","2 cups cold water","1 tsp ginger, grated","½ tsp cumin powder","¼ tsp black salt","A few curry leaves","½ tsp mustard seeds","1 green chilli","1 tsp oil","Fresh coriander","Salt to taste"],
    instructions: [
      "Blend yogurt and water until smooth.",
      "Add ginger, cumin, black salt, and regular salt. Mix.",
      "Heat oil in a small pan. Add mustard seeds until they pop.",
      "Add curry leaves and green chilli. Fry 30 seconds.",
      "Pour tempering over the chaas. Stir.",
      "Garnish with fresh coriander. Serve chilled.",
    ],
    prepTime: 5, cookTime: 3, servings: 3,
    cuisineType: "Gujarati", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Masala Chaas Buttermilk"),
  },
  {
    title: "Kesar Badam Shake", category: "mocktail",
    description: "Royal saffron and almond milkshake with rose water and cardamom — thick, golden and luxurious. Festival drink at its finest.",
    ingredients: ["15 almonds, soaked and peeled","A generous pinch of saffron in 2 tbsp warm milk","2 cups full-fat cold milk","3 tbsp sugar","½ tsp cardamom","1 tsp rose water","2 scoops vanilla ice cream","Slivered almonds and pistachios for garnish"],
    instructions: [
      "Blend soaked almonds with 2 tbsp milk to a smooth paste.",
      "Add cold milk, saffron milk, sugar, cardamom, and rose water. Blend until frothy.",
      "Add ice cream and blend again briefly.",
      "Pour into chilled glasses.",
      "Garnish with slivered almonds, pistachios and a saffron strand.",
    ],
    prepTime: 245, cookTime: 0, servings: 2,
    cuisineType: "North Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Kesar Badam Shake Saffron Almond"),
  },
  {
    title: "Jaljeera Soda", category: "mocktail",
    description: "Classic jal jeera concentrate lifted with sparkling soda — tangy, spiced, minty and wonderfully effervescent.",
    ingredients: ["2 tbsp jaljeera powder (or homemade concentrate)","2 tbsp tamarind water","1 tsp black salt","1 tsp sugar","Lemon juice","Cold soda water","Ice cubes","Mint and boondi for garnish"],
    instructions: [
      "Mix jaljeera powder (or concentrate) with tamarind water, black salt, sugar, and lemon juice.",
      "Taste and adjust — should be intensely spiced.",
      "Place 2 tbsp of concentrate in each glass.",
      "Add ice.",
      "Top with cold soda water.",
      "Garnish with mint, a few boondi, and a lemon wedge.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "North Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Jaljeera Soda Mocktail"),
  },
  {
    title: "Mango Ginger Lassi", category: "mocktail",
    description: "Spiced mango lassi with a warming ginger kick — the perfect balance of cooling and warming for year-round enjoyment.",
    ingredients: ["1 cup mango pulp","1 cup yogurt","½ cup milk","1-inch ginger, juiced","2 tbsp sugar","½ tsp cardamom","Ice cubes","Mango pieces and candied ginger for garnish"],
    instructions: [
      "Blend mango pulp, yogurt, milk, sugar, ginger juice, and cardamom until smooth.",
      "Taste — mango sweetness varies. Adjust sugar accordingly.",
      "Pour over ice.",
      "Garnish with mango pieces and ginger.",
    ],
    prepTime: 5, cookTime: 0, servings: 2,
    cuisineType: "Pan-Indian", dietaryTags: ["Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Mango Ginger Lassi"),
  },
  {
    title: "Paan Sharbat", category: "mocktail",
    description: "Refreshing betel leaf sharbat with fennel, gulkand and mint — India's most distinctive post-meal palate cleanser turned cooling drink.",
    ingredients: ["5 fresh betel (paan) leaves","2 tbsp gulkand (rose petal jam)","1 tbsp fennel seeds, soaked","A pinch of cardamom","2 tbsp sugar","2 cups cold water","Ice cubes","Rose petals and fennel for garnish"],
    instructions: [
      "Soak fennel seeds in water for 30 minutes.",
      "Blend paan leaves, gulkand, soaked fennel seeds, cardamom, and sugar with a little water.",
      "Strain through fine mesh.",
      "Mix with remaining cold water. Taste and adjust.",
      "Serve over ice.",
      "Garnish with rose petals and a few fennel seeds.",
    ],
    prepTime: 35, cookTime: 0, servings: 3,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Paan Sharbat Betel Leaf"),
  },
  {
    title: "Grape Mint Cooler", category: "mocktail",
    description: "Fresh grape juice muddled with mint, lime and chilled soda — deeply purple, sweet-tart and utterly elegant.",
    ingredients: ["2 cups fresh black grapes","10 mint leaves","1 lime, juiced","2 tbsp sugar","Soda water","Ice cubes","Grape clusters and mint for garnish"],
    instructions: [
      "Blend grapes until smooth. Strain through a sieve.",
      "Muddle mint with lime juice and sugar.",
      "Mix grape juice with mint mixture.",
      "Pour over ice in glasses.",
      "Top with soda water.",
      "Garnish with grape clusters and mint.",
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    cuisineType: "Fusion", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Grape Mint Cooler Mocktail"),
  },
  {
    title: "Sol Kadhi", category: "mocktail",
    description: "Goa and Konkan's iconic pink coconut milk and kokum digestive drink — velvety, gently tart and spiced with garlic and cumin.",
    ingredients: ["10 kokum pieces","1 cup thick coconut milk","2 cups water","1 garlic clove, crushed","½ tsp cumin powder","Green chilli, slit","Fresh coriander","Salt to taste"],
    instructions: [
      "Soak kokum in 1 cup warm water for 30 minutes. Squeeze and strain.",
      "Mix kokum water with coconut milk and remaining water.",
      "Add crushed garlic, cumin, green chilli, and salt.",
      "Whisk until the colour turns a beautiful pink from the kokum.",
      "Refrigerate 30 minutes.",
      "Serve cold, garnished with fresh coriander. Do not heat.",
    ],
    prepTime: 35, cookTime: 0, servings: 4,
    cuisineType: "Maharashtrian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Sol Kadhi Goan Kokum Coconut"),
  },
  {
    title: "Turmeric Ginger Lemonade", category: "mocktail",
    description: "Sunshine in a glass — fresh turmeric, ginger and lemon with honey and black pepper. The ultimate Indian wellness drink.",
    ingredients: ["1-inch fresh turmeric, juiced (or ½ tsp powder)","1-inch ginger, juiced","3 lemons, juiced","2 tbsp honey","A pinch of black pepper","3 cups cold water","Ice cubes","Lemon wheels and turmeric for garnish"],
    instructions: [
      "Juice fresh turmeric and ginger if available.",
      "Mix turmeric juice, ginger juice, lemon juice, honey, and black pepper.",
      "Add cold water. Stir vigorously.",
      "Taste and adjust sweetness with honey.",
      "Pour over ice.",
      "Garnish with lemon wheels and a tiny pinch of turmeric powder.",
    ],
    prepTime: 10, cookTime: 0, servings: 3,
    cuisineType: "Pan-Indian", dietaryTags: ["Vegan", "Gluten-Free"],
    imageUrl: null, youtubeUrl: yt("Turmeric Ginger Lemonade"),
  },
];
